<center> <img src = https://raw.githubusercontent.com/AndreyRysistov/DatasetsForPandas/main/hh%20label.jpg alt="drawing" style="width:400px;">

# <center> Проект: Анализ резюме из HeadHunter

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px

# Исследование структуры данных

1. Прочитайте данные с помощью библиотеки Pandas. Совет: перед чтением обратите внимание на разделитель внутри файла.

In [497]:
hh_database = pd.read_csv('D:\DS\data\dst-3.0_16_1_hh_database.csv', sep = ';')

<>:1: SyntaxWarning: invalid escape sequence '\D'
<>:1: SyntaxWarning: invalid escape sequence '\D'
C:\Users\1\AppData\Local\Temp\ipykernel_4108\1632024950.py:1: SyntaxWarning: invalid escape sequence '\D'
  hh_database = pd.read_csv('D:\DS\data\dst-3.0_16_1_hh_database.csv', sep = ';')

2. Выведите несколько первых (последних) строк таблицы, чтобы убедиться в том, что ваши данные не повреждены. Ознакомьтесь с признаками и их структурой.

In [498]:
display(hh_database.head(3))
hh_database.tail(3)

,"Пол, возраст",ЗП,Ищет работу на должность:,"Город, переезд, командировки",Занятость,График,Опыт работы,Последнее/нынешнее место работы,Последняя/нынешняя должность,Образование и ВУЗ,Обновление резюме,Авто
0,"Мужчина , 39 лет , родился 27 ноября 1979",29000 руб.,Системный администратор,"Советск (Калининградская область) , не готов к...","частичная занятость, проектная работа, полная ...","гибкий график, полный день, сменный график, ва...",Опыт работы 16 лет 10 месяцев Август 2010 — п...,"МАОУ ""СОШ № 1 г.Немана""",Системный администратор,Неоконченное высшее образование 2000 Балтийск...,16.04.2019 15:59,Имеется собственный автомобиль
1,"Мужчина , 60 лет , родился 20 марта 1959",40000 руб.,Технический писатель,"Королев , не готов к переезду , готов к редким...","частичная занятость, проектная работа, полная ...","гибкий график, полный день, сменный график, уд...",Опыт работы 19 лет 5 месяцев Январь 2000 — по...,Временный трудовой коллектив,"Менеджер проекта, Аналитик, Технический писатель",Высшее образование 1981 Военно-космическая ак...,12.04.2019 08:42,Не указано
2,"Женщина , 36 лет , родилась 12 августа 1982",20000 руб.,Оператор,"Тверь , не готова к переезду , не готова к ком...",полная занятость,полный день,Опыт работы 10 лет 3 месяца Октябрь 2004 — Де...,ПАО Сбербанк,Кассир-операционист,Среднее специальное образование 2002 Профессио...,16.04.2019 08:35,Не указано

,"Пол, возраст",ЗП,Ищет работу на должность:,"Город, переезд, командировки",Занятость,График,Опыт работы,Последнее/нынешнее место работы,Последняя/нынешняя должность,Образование и ВУЗ,Обновление резюме,Авто
44741,"Женщина , 48 лет , родилась 26 декабря 1970",40000 руб.,"Аналитик данных, Математик","Челябинск , готова к переезду , готова к редки...",полная занятость,"полный день, удаленная работа",Опыт работы 21 год 5 месяцев Январь 1998 — по...,"ОАО «ЧМК», Исследовательско-Технологический Це...",Начальник группы аналитики,Высшее образование 2000 Южно-Уральский госуда...,09.04.2019 05:07,Не указано
44742,"Мужчина , 24 года , родился 6 октября 1994",20000 руб.,Контент-менеджер,"Тамбов , не готов к переезду , не готов к кома...","частичная занятость, полная занятость",удаленная работа,Опыт работы 3 года 10 месяцев Контент-менедже...,IQ-Maxima,Менеджер проектов,Высшее образование 2015 Тамбовский государств...,26.04.2019 14:25,Имеется собственный автомобиль
44743,"Мужчина , 38 лет , родился 25 апреля 1980",120000 руб.,Руководитель проекта,"Москва , не готов к переезду , не готов к кома...",полная занятость,полный день,Опыт работы 15 лет 10 месяцев Руководитель пр...,ПАО ГК ТНС энерго,Руководитель отдела технической поддержки,Высшее образование 1997 Южно-Российский госуд...,05.07.2018 20:15,Не указано

In [500]:
hh_database.shape

(44744, 12)

3. Выведите основную информацию о числе непустых значений в столбцах и их типах в таблице.

In [226]:
hh_database.info()

<class 'pandas.DataFrame'>
RangeIndex: 44744 entries, 0 to 44743
Data columns (total 12 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   Пол, возраст                     44744 non-null  str
 1   ЗП                               44744 non-null  str
 2   Ищет работу на должность:        44744 non-null  str
 3   Город, переезд, командировки     44744 non-null  str
 4   Занятость                        44744 non-null  str
 5   График                           44744 non-null  str
 6   Опыт работы                      44576 non-null  str
 7   Последнее/нынешнее место работы  44743 non-null  str
 8   Последняя/нынешняя должность     44742 non-null  str
 9   Образование и ВУЗ                44744 non-null  str
 10  Обновление резюме                44744 non-null  str
 11  Авто                             44744 non-null  str
dtypes: str(12)
memory usage: 4.1 MB

4. Обратите внимание на информацию о числе непустых значений.

In [87]:
hh_database.notnull().sum()

Пол, возраст                       44744
ЗП                                 44744
Ищет работу на должность:          44744
Город, переезд, командировки       44744
Занятость                          44744
График                             44744
Опыт работы                        44576
Последнее/нынешнее место работы    44743
Последняя/нынешняя должность       44742
Образование и ВУЗ                  44744
Обновление резюме                  44744
Авто                               44744
dtype: int64

5. Выведите основную статистическую информацию о столбцах.

In [88]:
hh_database.describe(include=['object'])

C:\Users\1\AppData\Local\Temp\ipykernel_4108\1846862403.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  hh_database.describe(include=['object'])

,"Пол, возраст",ЗП,Ищет работу на должность:,"Город, переезд, командировки",Занятость,График,Опыт работы,Последнее/нынешнее место работы,Последняя/нынешняя должность,Образование и ВУЗ,Обновление резюме,Авто
count,44744,44744,44744,44744,44744,44744,44576,44743,44742,44744,44744,44744
unique,16003,690,14929,10063,38,47,44413,30214,16927,40148,18838,2
top,"Мужчина , 32 года , родился 17 сентября 1986",50000 руб.,Системный администратор,"Москва , не готов к переезду , не готов к кома...",полная занятость,полный день,Опыт работы 10 лет 8 месяцев Апрель 2018 — по...,Индивидуальное предпринимательство / частная п...,Системный администратор,Высшее образование 2014 Московский технически...,07.05.2019 09:50,Не указано
freq,18,4064,3099,1261,30026,22727,3,935,2062,4,25,32268

# Преобразование данных

1. Начнем с простого - с признака **"Образование и ВУЗ"**. Его текущий формат это: **<Уровень образования год выпуска ВУЗ специальность...>**. Например:
* Высшее образование 2016 Московский авиационный институт (национальный исследовательский университет)...
* Неоконченное высшее образование 2000  Балтийская государственная академия рыбопромыслового флота…
Нас будет интересовать только уровень образования.

Создайте с помощью функции-преобразования новый признак **"Образование"**, который должен иметь 4 категории: "высшее", "неоконченное высшее", "среднее специальное" и "среднее".

Выполните преобразование, ответьте на контрольные вопросы и удалите признак "Образование и ВУЗ".

Совет: обратите внимание на структуру текста в столбце **"Образование и ВУЗ"**. Гарантируется, что текущий уровень образования соискателя всегда находится в первых 2ух слов и начинается с заглавной буквы. Воспользуйтесь этим.

*Совет: проверяйте полученные категории, например, с помощью метода unique()*

In [501]:
def education(option):    
# На вход получает строку из таблицы из столбца "Образование и Вуз"
# Изменяем регистр строки на нижний
# Преобразуем список в строку с разделителем " "
# Получаем срез первые 2 элемента списка и преобразуем обратно в строку
    option = option.lower()
    option_list = option.split(' ')
    option_list = option_list[:2]
    education_type = ' '.join(option_list)
# Проверяем условие на те типы, где нужно вывести 1 слово
# В противном случае возвращаем готовый результат
    if education_type == 'среднее образование':
        return 'среднее'
    elif education_type == 'высшее образование':
        return 'высшее'
    else:
        return education_type

In [502]:
# Проверяем работу функции
print(education('Среднее специальное образование 2017 Башкирск'))
print(education('Неоконченное высшее образование 2016 Новосиби'))
print(education('Высшее образование 2011 Московский Государстве'))
print(education('Среднее образование 2011 Московский Государстве'))

среднее специальное
неоконченное высшее
высшее
среднее

In [503]:
hh_database['Образование'] = hh_database['Образование и ВУЗ'].apply(education)
display(hh_database['Образование'].value_counts())

Образование
высшее                 33863
среднее специальное     5765
неоконченное высшее     4557
среднее                  559
Name: count, dtype: int64

In [504]:
# Удаляем признак "Образование и ВУЗ"
hh_database = hh_database.drop('Образование и ВУЗ', axis=1)
display(hh_database.head(1))

,"Пол, возраст",ЗП,Ищет работу на должность:,"Город, переезд, командировки",Занятость,График,Опыт работы,Последнее/нынешнее место работы,Последняя/нынешняя должность,Обновление резюме,Авто,Образование
0,"Мужчина , 39 лет , родился 27 ноября 1979",29000 руб.,Системный администратор,"Советск (Калининградская область) , не готов к...","частичная занятость, проектная работа, полная ...","гибкий график, полный день, сменный график, ва...",Опыт работы 16 лет 10 месяцев Август 2010 — п...,"МАОУ ""СОШ № 1 г.Немана""",Системный администратор,16.04.2019 15:59,Имеется собственный автомобиль,неоконченное высшее

2. Теперь нас интересует столбец **"Пол, возраст"**. Сейчас он представлен в формате **<Пол , возраст , дата рождения >**. Например:
* Мужчина , 39 лет , родился 27 ноября 1979 
* Женщина , 21 год , родилась 13 января 2000
Как вы понимаете, нам необходимо выделить каждый параметр в отдельный столбец.

Создайте два новых признака **"Пол"** и **"Возраст"**. При этом важно учесть:
* Признак пола должен иметь 2 уникальных строковых значения: 'М' - мужчина, 'Ж' - женщина. 
* Признак возраста должен быть представлен целыми числами.

Выполните преобразование, ответьте на контрольные вопросы и удалите признак **"Пол, возраст"** из таблицы.

*Совет: обратите внимание на структуру текста в столбце, в части на то, как разделены параметры пола, возраста и даты рождения между собой - символом ' , '. 
Гарантируется, что структура одинакова для всех строк в таблице. Вы можете воспользоваться этим.*

In [505]:
# Функция для определения пола
def gender(option):    
# На вход получает строку из таблицы из столбца "Пол, возраст"
# Преобразуем список в строку с разделителем ","
# Получаем срез первый 1 элемента списка
    option_list = option.split(',')
    gender_var = option_list[0]
    return gender_var[0]

In [506]:
# Проверяем работу функции
print(gender('Мужчина , 39 лет , родился 27 ноября 1979'))
print(gender('Женщина , 21 год , родилась 13 января 2000'))

М
Ж

In [507]:
# Применяем функцию к столбцу "Пол, возраст" и создаем новый признак "Пол"
hh_database['Пол'] = hh_database['Пол, возраст'].apply(gender)
display(hh_database['Пол'].value_counts())

Пол
М    36211
Ж     8533
Name: count, dtype: int64

In [508]:
print(round(hh_database['Пол'].value_counts(normalize=True)['Ж'] * 100, 2))

19.07

In [509]:
# Функция для получения возраста
def age(option):    
# На вход получает строку из таблицы из столбца "Пол, возраст"
# Преобразуем список в строку с разделителем ","
# Получаем  2 элемент списка- возраст
# Из этого элемента списка вычленяем число
    option_list = option.split(',')
    age = option_list[1]
    age = ''.join(filter(str.isdigit, age))

    return int(age)

In [510]:
# Проверяем работу функции
print(age('Мужчина ,  24 года , родился 6 октября 1994'))
print(age('Женщина ,  48 лет , родилась 26 декабря 1970'))

24
48

In [511]:
# Применяем функцию к столбцу "Пол, возраст" и создаем новый признак "Возраст"
hh_database['Возраст'] = hh_database['Пол, возраст'].apply(age)
display(hh_database['Возраст'].mean())

np.float64(32.19674146254246)

In [512]:
# Удаляем признак "Пол, возраст"
hh_database = hh_database.drop('Пол, возраст', axis=1)

In [513]:
hh_database.info()

<class 'pandas.DataFrame'>
RangeIndex: 44744 entries, 0 to 44743
Data columns (total 13 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   ЗП                               44744 non-null  str
 1   Ищет работу на должность:        44744 non-null  str
 2   Город, переезд, командировки     44744 non-null  str
 3   Занятость                        44744 non-null  str
 4   График                           44744 non-null  str
 5   Опыт работы                      44576 non-null  str
 6   Последнее/нынешнее место работы  44743 non-null  str
 7   Последняя/нынешняя должность     44742 non-null  str
 8   Обновление резюме                44744 non-null  str
 9   Авто                             44744 non-null  str
 10  Образование                      44744 non-null  str
 11  Пол                              44744 non-null  str
 12  Возраст                          44744 non-null  int64
dtypes: int64(1), str(12)
memory usage: 4.4 MB

3. Следующим этапом преобразуем признак **"Опыт работы"**. Его текущий формат - это: **<Опыт работы: n лет m месяцев, периоды работы в различных компаниях…>**. 

Из столбца нам необходимо выделить общий опыт работы соискателя в месяцах, новый признак назовем "Опыт работы (месяц)"

Для начала обсудим условия решения задачи:
* Во-первых, в данном признаке есть пропуски. Условимся, что если мы встречаем пропуск, оставляем его как есть (функция-преобразование возвращает NaN)
* Во-вторых, в данном признаке есть скрытые пропуски. Для некоторых соискателей в столбце стоит значения "Не указано". Их тоже обозначим как NaN (функция-преобразование возвращает NaN)
* В-третьих, нас не интересует информация, которая описывается после указания опыта работы (периоды работы в различных компаниях)
* В-четвертых, у нас есть проблема: опыт работы может быть представлен только в годах или только месяцах. Например, можно встретить следующие варианты:
    * Опыт работы 3 года 2 месяца…
    * Опыт работы 4 года…
    * Опыт работы 11 месяцев…
    * Учитывайте эту особенность в вашем коде

Учитывайте эту особенность в вашем коде

В результате преобразования у вас должен получиться столбец, содержащий информацию о том, сколько месяцев проработал соискатель.
Выполните преобразование, ответьте на контрольные вопросы и удалите столбец **"Опыт работы"** из таблицы.

In [514]:
def work_experience(str):
    if str is np.nan or str == 'Не указано':
        return None
    
    year_in_words=['год', 'года', 'лет']
    month_in_words=['месяц', 'месяца', 'месяцев']
    
    str_splitted = str.split(' ')[:7]
    years = 0
    months = 0
    for index, item in enumerate (str_splitted):
        if item in year_in_words:
            years = int(str_splitted[index-1])
        if item in month_in_words:
            months = int(str_splitted[index-1])
            
    return int(years*12 + months)

In [515]:
# Применяем функцию к столбцу "Опыт работы" и создаем новый признак "Опыт работы (месяц)"
hh_database['Опыт работы (месяц)'] = hh_database['Опыт работы'].apply(work_experience)

In [516]:
print('Медианный опыт работы (в месяцах) в таблице равен', round(hh_database['Опыт работы (месяц)'].median()))

Медианный опыт работы (в месяцах) в таблице равен 100

In [517]:
# Удаляем столбец
hh_database.drop('Опыт работы', axis=1, inplace=True)

4. Хорошо идем! Следующий на очереди признак "Город, переезд, командировки". Информация в нем представлена в следующем виде: **<Город , (метро) , готовность к переезду (города для переезда) , готовность к командировкам>**. В скобках указаны необязательные параметры строки. Например, можно встретить следующие варианты:

* Москва , не готов к переезду , готов к командировкам
* Москва , м. Беломорская , не готов к переезду, не готов к командировкам
* Воронеж , готов к переезду (Сочи, Москва, Санкт-Петербург) , готов к командировкам

Создадим отдельные признаки **"Город"**, **"Готовность к переезду"**, **"Готовность к командировкам"**. При этом важно учесть:

* Признак **"Город"** должен содержать только 4 категории: "Москва", "Санкт-Петербург" и "город-миллионник" (их список ниже), остальные обозначьте как "другие".

    Список городов-миллионников:
    
   <code>million_cities = ['Новосибирск', 'Екатеринбург','Нижний Новгород','Казань', 'Челябинск','Омск', 'Самара', 'Ростов-на-Дону', 'Уфа', 'Красноярск', 'Пермь', 'Воронеж','Волгоград']
    </code>
    Инфорация о метро, рядом с которым проживает соискатель нас не интересует.
* Признак **"Готовность к переезду"** должен иметь два возможных варианта: True или False. Обратите внимание, что возможны несколько вариантов описания готовности к переезду в признаке "Город, переезд, командировки". Например:
    * … , готов к переезду , …
    * … , не готова к переезду , …
    * … , готова к переезду (Москва, Санкт-Петербург, Ростов-на-Дону)
    * … , хочу переехать (США) , …
    
    Нас интересует только сам факт возможности или желания переезда.
* Признак **"Готовность к командировкам"** должен иметь два возможных варианта: True или False. Обратите внимание, что возможны несколько вариантов описания готовности к командировкам в признаке "Город, переезд, командировки". Например:
    * … , готов к командировкам , … 
    * … , готова к редким командировкам , …
    * … , не готов к командировкам , …
    
    Нас интересует только сам факт готовности к командировке.
    
    Еще один важный факт: при выгрузки данных у некоторых соискателей "потерялась" информация о готовности к командировкам. Давайте по умолчанию будем считать, что такие соискатели не готовы к командировкам.
    
Выполните преобразования и удалите столбец **"Город, переезд, командировки"** из таблицы.

*Совет: обратите внимание на то, что структура текста может меняться в зависимости от указания ближайшего метро. Учите это, если будете использовать порядок слов в своей программе.*

In [518]:
def city(str):
    million_cities = ['Новосибирск', 'Екатеринбург','Нижний Новгород','Казань', 'Челябинск','Омск', 'Самара', 'Ростов-на-Дону', 'Уфа', 'Красноярск', 'Пермь', 'Воронеж','Волгоград']
    cities = str.split(' , ')[0]
    if cities == 'Москва':
        return 'Москва'
    elif cities == 'Санкт-Петербург':
        return 'Санкт-Петербург'
    elif cities in million_cities:
        return 'город-миллионник'
    else:
        return 'другие'

In [519]:
hh_database['Город'] = hh_database['Город, переезд, командировки'].apply(city)

In [520]:
def relocation(str):
    options = str.split(' , ')[1]
    options_splitted = options.split(' ')[0]
# делаем проверку, если 2 элемент списка - метро, переходим к 3 элементу списка и работаем с ним
    if options_splitted == 'м.':
        new_options = str.split(' , ')[2]
        new_options_splitted = new_options.split(' ')[0]
        if new_options_splitted == 'не':
            return False
        else:
            return True
# во всех остальных случаях работаем со 2 элементом списка
    else:
        if options_splitted == 'не':
            return False
        else:
            return True

In [521]:
# Проверяем работу функции
relocation('Москва , м. Беломорская , готов к переезду, не готов к командировкам')

True

In [522]:
hh_database['Готовность к переезду'] = hh_database['Город, переезд, командировки'].apply(relocation)

In [523]:
def business_trip(str):
# делаем проверку, если 2 элемент списка - метро, переходим к 4 элементу списка и работаем с ним
    str_list = str.split(' , ')
    # Убедимся, что список достаточно длинный, чтобы избежать IndexError, 
    # для случая когда данные о коммандировках потерялись
    if len(str_list) < 3: 
        return False
    # Делаем проверку, есть ли метро в списке, чтобы понимать к какому элементу списка обращаться
    if len(str_list) == 4:
        trip_options = str.split(' , ')[3]
        trp_options_splitted = trip_options.split(' ')[0]
        if trp_options_splitted == 'не':
            return False
        else:
            return True
# во всех остальных случаях работаем с 3 элементом списка
    else:
        t_options = str.split(' , ')[2]
        t_options_splitted = t_options.split(' ')[0]
        if t_options_splitted == 'не':
            return False
        else:
            return True

In [524]:
# Проверяем работу функции
business_trip('Москва ,  м. Площадь Ильича , готова к переезду (Москва) , не готова к редким командировкам ')

False

In [525]:
hh_database['Готовность к командировкам'] = hh_database['Город, переезд, командировки'].apply(business_trip)

In [526]:
hh_database['Город'].value_counts(normalize=True)

Город
Москва              0.371469
другие              0.354327
город-миллионник    0.163866
Санкт-Петербург     0.110339
Name: proportion, dtype: float64

In [527]:
print(round
      (hh_database[(hh_database['Готовность к переезду'] == True) & 
                   (hh_database['Готовность к командировкам']== True)
                  ].shape[0] / hh_database.shape[0] *100))

50

In [528]:
# Удаляем столбец
hh_database.drop('Город, переезд, командировки', axis=1, inplace=True)

5. Рассмотрим поближе признаки **"Занятость"** и **"График"**. Сейчас признаки представляют собой набор категорий желаемой занятости (полная занятость, частичная занятость, проектная работа, волонтерство, стажировка) и желаемого графика работы (полный день, сменный график, гибкий график, удаленная работа, вахтовый метод).
На сайте hh.ru соискатель может указывать различные комбинации данных категорий, например:
* полная занятость, частичная занятость
* частичная занятость, проектная работа, волонтерство
* полный день, удаленная работа
* вахтовый метод, гибкий график, удаленная работа, полная занятость

Такой вариант признаков имеет множество различных комбинаций, а значит множество уникальных значений, что мешает анализу. Нужно это исправить!

Давайте создадим признаки-мигалки для каждой категории: если категория присутствует в списке желаемых соискателем, то в столбце на месте строки рассматриваемого соискателя ставится True, иначе - False.

Такой метод преобразования категориальных признаков называется One Hot Encoding и его схема представлена на рисунке ниже:
<img src=https://raw.githubusercontent.com/AndreyRysistov/DatasetsForPandas/main/ohe.jpg>
Выполните данное преобразование для признаков "Занятость" и "График", ответьте на контрольные вопросы, после чего удалите их из таблицы

In [529]:
def employment(row):
    text = row['Занятость']
    # обработка (можно сразу вернуть кортеж)
    return ( 'полная занятость' in text,
             'частичная занятость' in text,
             'проектная работа' in text,
             'стажировка' in text,
             'волонтерство' in text )

In [530]:
new_cols = ['полная занятость', 'частичная занятость', 'проектная работа', 'стажировка', 'волонтерство']
hh_database[new_cols] = hh_database[['Занятость']].apply(employment, axis=1, result_type='expand')

In [532]:
def schedule(row):
    text = row['График']
    # обработка (можно сразу вернуть кортеж)
    return ( 'полный день' in text,
             'сменный график' in text,
             'гибкий график' in text,
             'удаленная работа' in text,
             'вахтовый метод' in text )

In [534]:
new_cols = ['полный день', 'сменный график', 'гибкий график', 'удаленная работа', 'вахтовый метод']
hh_database[new_cols] = hh_database[['График']].apply(schedule, axis=1, result_type='expand')

In [540]:
mask = (hh_database['проектная работа'] == True) & (hh_database['волонтерство'] == True)
hh_database[mask].shape[0]

436

In [541]:
mask = (hh_database['вахтовый метод'] == True) & (hh_database['гибкий график'] == True)
hh_database[mask].shape[0]

2311

In [542]:
hh_database.drop('Занятость', axis=1, inplace=True)
hh_database.drop('График', axis=1, inplace=True)

6. (2 балла) Наконец, мы добрались до самого главного и самого важного - признака заработной платы **"ЗП"**. 
В чем наша беда? В том, что помимо желаемой заработной платы соискатель указывает валюту, в которой он бы хотел ее получать, например:
* 30000 руб.
* 50000 грн.
* 550 USD

Нам бы хотелось видеть заработную плату в единой валюте, например, в рублях. Возникает вопрос, а где взять курс валют по отношению к рублю?

На самом деле язык Python имеет в арсенале огромное количество возможностей получения данной информации, от обращения к API Центробанка, до использования специальных библиотек, например pycbrf. Однако, это не тема нашего проекта.

Поэтому мы пойдем в лоб: обратимся к специальным интернет-ресурсам для получения данных о курсе в виде текстовых файлов. Например, MDF.RU, данный ресурс позволяет удобно экспортировать данные о курсах различных валют и акций за указанные периоды в виде csv файлов. Мы уже сделали выгрузку курсов валют, которые встречаются в наших данных за период с 29.12.2017 по 05.12.2019. Скачать ее вы можете **на платформе**

Создайте новый DataFrame из полученного файла. В полученной таблице нас будут интересовать столбцы:
* "currency" - наименование валюты в ISO кодировке,
* "date" - дата, 
* "proportion" - пропорция, 
* "close" - цена закрытия (последний зафиксированный курс валюты на указанный день).


Перед вами таблица соответствия наименований иностранных валют в наших данных и их общепринятых сокращений, которые представлены в нашем файле с курсами валют. Пропорция - это число, за сколько единиц валюты указан курс в таблице с курсами. Например, для казахстанского тенге курс на 20.08.2019 составляет 17.197 руб. за 100 тенге, тогда итоговый курс равен - 17.197 / 100 = 0.17197 руб за 1 тенге.
Воспользуйтесь этой информацией в ваших преобразованиях.

<img src=https://raw.githubusercontent.com/AndreyRysistov/DatasetsForPandas/main/table.jpg>


Осталось только понять, откуда брать дату, по которой определяется курс? А вот же она - в признаке **"Обновление резюме"**, в нем содержится дата и время, когда соискатель выложил текущий вариант своего резюме. Нас интересует только дата, по ней бы и будем сопоставлять курсы валют.

Теперь у нас есть вся необходимая информация для того, чтобы создать признак "ЗП (руб)" - заработная плата в рублях.

После ответа на контрольные вопросы удалите исходный столбец заработной платы "ЗП" и все промежуточные столбцы, если вы их создавали.

Итак, давайте обсудим возможный алгоритм преобразования: 
1. Перевести признак "Обновление резюме" из таблицы с резюме в формат datetime и достать из него дату. В тот же формат привести признак "date" из таблицы с валютами.
2. Выделить из столбца "ЗП" сумму желаемой заработной платы и наименование валюты, в которой она исчисляется. Наименование валюты перевести в стандарт ISO согласно с таблицей выше.
3. Присоединить к таблице с резюме таблицу с курсами по столбцам с датой и названием валюты (подумайте, какой тип объединения надо выбрать, чтобы в таблице с резюме сохранились данные о заработной плате, изначально представленной в рублях). Значение close для рубля заполнить единицей 1 (курс рубля самого к себе)
4. Умножить сумму желаемой заработной платы на присоединенный курс валюты (close) и разделить на пропорцию (обратите внимание на пропуски после объединения в этих столбцах), результат занести в новый столбец "ЗП (руб)".

In [ ]:
exchange = pd.read_csv('data/ExchangeRates.csv', sep = ',')

  currency per      date   time    close  vol  proportion
0      USD   D  29/12/17  00:00  57.6291    0           1
1      USD   D  30/12/17  00:00  57.6002    0           1
2      USD   D  31/12/17  00:00  57.6002    0           1

In [557]:
exchange.drop('per', axis=1, inplace=True)
exchange.drop('time', axis=1, inplace=True)
exchange.drop('vol', axis=1, inplace=True)
exchange.head(3)

  currency       date    close  proportion
0      USD 2017-12-29  57.6291           1
1      USD 2017-12-30  57.6002           1
2      USD 2017-12-31  57.6002           1

In [588]:
hh_database['Обновление резюме'] = pd.to_datetime(hh_database['Обновление резюме'], dayfirst=True)

In [589]:
hh_database['Обновление резюме'] = hh_database['Обновление резюме'].dt.date

In [590]:
exchange['date'] = pd.to_datetime(exchange['date'], dayfirst=True)

In [ ]:
# Выделяем из столбца ЗП цифру
def sum(str):
    sum = str.split(' ')[0]
    return int(sum)

In [ ]:
# Заносим в промежуточный столбец цифру зп
hh_database['цифра зп'] = hh_database['ЗП'].apply(sum)

In [569]:
def currency(str):
    cur= str.split(' ')[1]
    if cur == 'грн':
        return 'UAH'
    elif cur == 'белруб':
        return 'BYN'
    elif cur == 'сум':
        return 'UZS'
    elif cur == 'руб.':
        return 'RUB'
    else:
        return cur

In [570]:
# Заносим в промежуточный столбец валюту, в которой указана зп
hh_database['валюта'] = hh_database['ЗП'].apply(currency)

In [575]:
hh_database.head(1)

,ЗП,Ищет работу на должность:,Последнее/нынешнее место работы,Последняя/нынешняя должность,Обновление резюме,Авто,Образование,Пол,Возраст,Опыт работы (месяц),...,проектная работа,стажировка,волонтерство,полный день,сменный график,гибкий график,удаленная работа,вахтовый метод,цифра зп,валюта
0,29000 руб.,Системный администратор,"МАОУ ""СОШ № 1 г.Немана""",Системный администратор,2019-04-16,Имеется собственный автомобиль,неоконченное высшее,М,39,202.0,...,True,False,False,True,True,True,True,True,29000,RUB

In [574]:
exchange.head(3)

  currency       date    close  proportion
0      USD 2017-12-29  57.6291           1
1      USD 2017-12-30  57.6002           1
2      USD 2017-12-31  57.6002           1

In [591]:
merged = hh_database.merge(
    exchange,
    left_on = ['Обновление резюме','валюта'],
    right_on = ['date', 'currency'],
    how='left'
)
display(merged.head())

ValueError: You are trying to merge on object and datetime64[us] columns for key 'Обновление резюме'. If you wish to proceed you should use pd.concat

# Исследование зависимостей в данных

1. Постройте распределение признака **"Возраст"**. Опишите распределение, отвечая на следующие вопросы: чему равна мода распределения, каковы предельные значения признака, в каком примерном интервале находится возраст большинства соискателей? Есть ли аномалии для признака возраста, какие значения вы бы причислили к их числу?
*Совет: постройте гистограмму и коробчатую диаграмму рядом.*

In [12]:
# ваш код здесь

ваши выводы по графику здесь

2. Постройте распределение признака **"Опыт работы (месяц)"**. Опишите данное распределение, отвечая на следующие вопросы: чему равна мода распределения, каковы предельные значения признака, в каком примерном интервале находится опыт работы большинства соискателей? Есть ли аномалии для признака опыта работы, какие значения вы бы причислили к их числу?
*Совет: постройте гистограмму и коробчатую диаграмму рядом.*

In [13]:
# ваш код здесь

ваши выводы здесь

3. Постройте распределение признака **"ЗП (руб)"**. Опишите данное распределение, отвечая на следующие вопросы: каковы предельные значения признака, в каком примерном интервале находится заработная плата большинства соискателей? Есть ли аномалии для признака возраста? Обратите внимание на гигантские размеры желаемой заработной платы.
*Совет: постройте гистограмму и коробчатую диаграмму рядом.*

In [14]:
# ваш код здесь

ваши выводы здесь

4. Постройте диаграмму, которая показывает зависимость **медианной** желаемой заработной платы (**"ЗП (руб)"**) от уровня образования (**"Образование"**). Используйте для диаграммы данные о резюме, где желаемая заработная плата меньше 1 млн рублей.
*Сделайте выводы по представленной диаграмме: для каких уровней образования наблюдаются наибольшие и наименьшие уровни желаемой заработной платы? Как вы считаете, важен ли признак уровня образования при прогнозировании заработной платы?*

In [15]:
# ваш код здесь

ваши выводы здесь

5. Постройте диаграмму, которая показывает распределение желаемой заработной платы (**"ЗП (руб)"**) в зависимости от города (**"Город"**). Используйте для диаграммы данные о резюме, где желая заработная плата меньше 1 млн рублей.
*Сделайте выводы по полученной диаграмме: как соотносятся медианные уровни желаемой заработной платы и их размах в городах? Как вы считаете, важен ли признак города при прогнозировании заработной платы?*

In [16]:
# ваш код здесь

ваши выводы здесь

6. Постройте **многоуровневую столбчатую диаграмму**, которая показывает зависимость медианной заработной платы (**"ЗП (руб)"**) от признаков **"Готовность к переезду"** и **"Готовность к командировкам"**. Проанализируйте график, сравнив уровень заработной платы в категориях.

In [17]:
# ваш код здесь

In [18]:
ваши выводы здесь

SyntaxError: invalid syntax (1506124366.py, line 1)

7. Постройте сводную таблицу, иллюстрирующую зависимость **медианной** желаемой заработной платы от возраста (**"Возраст"**) и образования (**"Образование"**). На полученной сводной таблице постройте **тепловую карту**. Проанализируйте тепловую карту, сравнив показатели внутри групп.

In [ ]:
# ваш код здесь

ваши выводы здесь

8. Постройте **диаграмму рассеяния**, показывающую зависимость опыта работы (**"Опыт работы (месяц)"**) от возраста (**"Возраст"**). Опыт работы переведите из месяцев в года, чтобы признаки были в едином масштабе. Постройте на графике дополнительно прямую, проходящую через точки (0, 0) и (100, 100). Данная прямая соответствует значениям, когда опыт работы равен возрасту человека. Точки, лежащие на этой прямой и выше нее - аномалии в наших данных (опыт работы больше либо равен возрасту соискателя)

In [ ]:
# ваш код здесь

ваши выводы здесь

**Дополнительные баллы**

Для получения 2 дополнительных баллов по разведывательному анализу постройте еще два любых содержательных графика или диаграммы, которые помогут проиллюстрировать влияние признаков/взаимосвязь между признаками/распределения признаков. Приведите выводы по ним. Желательно, чтобы в анализе участвовали признаки, которые мы создавали ранее в разделе "Преобразование данных".

In [ ]:
# ваш код здесь

ваши выводы здесь

# Очистка данных

1. Начнем с дубликатов в наших данных. Найдите **полные дубликаты** в таблице с резюме и удалите их.

In [ ]:
# ваш код здесь

2. Займемся пропусками. Выведите информацию **о числе пропусков** в столбцах.

In [ ]:
# ваш код здесь

3. Итак, у нас есть пропуски в 3ех столбцах: **"Опыт работы (месяц)"**, **"Последнее/нынешнее место работы"**, **"Последняя/нынешняя должность"**. Поступим следующим образом: удалите строки, где есть пропуск в столбцах с местом работы и должностью. Пропуски в столбце с опытом работы заполните **медианным** значением.

In [ ]:
# ваш код здесь

4. Мы добрались до ликвидации выбросов. Сначала очистим данные вручную. Удалите резюме, в которых указана заработная плата либо выше 1 млн. рублей, либо ниже 1 тыс. рублей.

In [ ]:
# ваш код здесь

5. В процессе разведывательного анализа мы обнаружили резюме, в которых **опыт работы в годах превышал возраст соискателя**. Найдите такие резюме и удалите их из данных

In [ ]:
# ваш код здесь

6. В результате анализа мы обнаружили потенциальные выбросы в признаке **"Возраст"**. Это оказались резюме людей чересчур преклонного возраста для поиска работы. Попробуйте построить распределение признака в **логарифмическом масштабе**. Добавьте к графику линии, отображающие **среднее и границы интервала метода трех сигм**. Напомним, сделать это можно с помощью метода axvline. Например, для построение линии среднего будет иметь вид:

`histplot.axvline(log_age.mean(), color='k', lw=2)`

В какую сторону асимметрично логарифмическое распределение? Напишите об этом в комментарии к графику.
Найдите выбросы с помощью метода z-отклонения и удалите их из данных, используйте логарифмический масштаб. Давайте сделаем послабление на **1 сигму** (возьмите 4 сигмы) в **правую сторону**.

Выведите таблицу с полученными выбросами и оцените, с каким возрастом соискатели попадают под категорию выбросов?

In [ ]:
# ваш код здесь

ваш коммментарий здесь