In [3]:
import pandas as pd

pd.Series()

In [4]:
#Для создания объекта Series используется команда pd.Series()
#Способ 1 — из списка с использованием параметров функции pd.Series()
countries = pd.Series(
    data = ['Англия', 'Канада', 'США', 'Россия', 'Украина', 'Беларусь', 'Казахстан'],
    index = ['UK', 'CA', 'US', 'RU', 'UA', 'BY', 'KZ'],
    name = 'countries'
)
display(countries)
#Если оставить параметр index пустым, то метки будут присвоены автоматически в виде порядковых номеров элементов
#Способ 2 — из словаря, в котором ключами являются будущие метки, 
# а значениями — будущие значения Series, при этом использование параметра name также возможно
countries = pd.Series({
    'UK': 'Англия',
    'CA': 'Канада',
    'US' : 'США',
    'RU': 'Россия',
    'UA': 'Украина',
    'BY': 'Беларусь',
    'KZ': 'Казахстан'},
    name = 'countries'
)
display(countries)

UK       Англия
CA       Канада
US          США
RU       Россия
UA      Украина
BY     Беларусь
KZ    Казахстан
Name: countries, dtype: str

UK       Англия
CA       Канада
US          США
RU       Россия
UA      Украина
BY     Беларусь
KZ    Казахстан
Name: countries, dtype: str

In [5]:
#Доступ к данным в Series
print(countries.loc[['US', 'RU', 'UK']])
print(countries.iloc[6])
print(countries.iloc[1:4])

US       США
RU    Россия
UK    Англия
Name: countries, dtype: str
Казахстан
CA    Канада
US       США
RU    Россия
Name: countries, dtype: str

pd.DataFrame()

In [6]:
# Создание DataFrame
# Способ 1. из словаря, ключами которого являются имена столбцов будущей таблицы, 
# а значениями — списки, в которых хранится содержимое этих столбцов
countries_df = pd.DataFrame({
    'country': ['Англия', 'Канада', 'США', 'Россия', 'Украина', 'Беларусь', 'Казахстан'],
    'population': [56.29, 38.05, 322.28, 146.24, 45.5, 9.5, 17.04],
    'area': [133396, 9984670, 9826630, 17125191, 603628, 207600, 2724902]
})
countries_df.index = ['UK', 'CA', 'US', 'RU', 'UA', 'BY', 'KZ']
display(countries_df)
# Способ 2. из вложенного списка, внутренние списки которого будут являться строками новой таблицы:
countries_df = pd.DataFrame(
    data = [
        ['Англия', 56.29, 133396],
        ['Канада', 38.05, 9984670],
        ['США', 322.28, 9826630],
        ['Россия', 146.24, 17125191],
        ['Украина', 45.5, 603628],
        ['Беларусь', 9.5, 207600],
        ['Казахстан', 17.04, 2724902]
    ],
    columns= ['country', 'population', 'area'],
    index = ['UK', 'CA', 'US', 'RU', 'UA', 'BY', 'KZ']
)
display(countries_df)

      country  population      area
UK     Англия       56.29    133396
CA     Канада       38.05   9984670
US        США      322.28   9826630
RU     Россия      146.24  17125191
UA    Украина       45.50    603628
BY   Беларусь        9.50    207600
KZ  Казахстан       17.04   2724902

      country  population      area
UK     Англия       56.29    133396
CA     Канада       38.05   9984670
US        США      322.28   9826630
RU     Россия      146.24  17125191
UA    Украина       45.50    603628
BY   Беларусь        9.50    207600
KZ  Казахстан       17.04   2724902

In [7]:
# Движение по строкам в таблице обозначается axis с индексом 0, а движение по столбцам — axis с индексом 1
# Считаем среднее по строкам (axis = 0) в каждом столбце:
countries_df.mean(axis=0, numeric_only=True)
# Считаем среднее по столбцам (axis = 1) в каждой строке:
countries_df.mean(axis=1, numeric_only=True)

UK      66726.145
CA    4992354.025
US    4913476.140
RU    8562668.620
UA     301836.750
BY     103804.750
KZ    1362459.520
dtype: float64

In [8]:
# Доступ к данным в DataFrame
countries_df.population
# Однако использование такого способа возможно только тогда, когда имя столбца указано без пробелов
countries_df['population']
countries_df.loc['UK', 'area']
countries_df.loc['RU', ['population', 'area']]
countries_df.loc[['UA', 'BY', 'KZ'],['population', 'area']]
countries_df.iloc[4:8, 1:3]

    population     area
UA       45.50   603628
BY        9.50   207600
KZ       17.04  2724902

Экспорт данных в формат csv осуществляется с помощью метода DataFrame to_csv()

In [9]:
#path_or_buf — путь до файла, в который будет записан DataFrame (например, data/my_data.csv);
#sep — разделитель данных в выходном файле (по умолчанию ',');
#decimal — разделитель чисел на целую и дробную части в выходном файле (по умолчанию '.');
#columns — список столбцов, которые нужно записать в файл (по умолчанию записываются все столбцы);
#index — параметр, определяющий, требуется ли создавать дополнительный столбец 
# с индексами строк в файле (по умолчанию True).
countries_df = pd.DataFrame({
    'country': ['Англия', 'Канада', 'США', 'Россия', 'Украина', 'Беларусь', 'Казахстан'],
    'population': [56.29, 38.05, 322.28, 146.24, 45.5, 9.5, 17.04],
    'area': [133396, 9984670, 9826630, 17125191, 603628, 207600, 2724902]
})

countries_df.to_csv('data/countries.csv', index=False, sep=';')

Для чтения таблицы из csv-файла используется функция модуля Pandas read_csv

In [10]:
#filepath_or_buffer — путь до файла, который мы читаем;
#sep — разделитель данных (по умолчанию ',');
#decimal — разделитель чисел на целую и дробную часть в выходном файле (по умолчанию '.');
#names — список с названиями столбцов для чтения;
#skiprows — количество строк в файле, которые нужно пропустить 
# (например, файл может содержать служебную информацию, которая нам не нужна).
countries_data = pd.read_csv('data/countries.csv', sep=';')

Чтение csv-файла по ссылке

In [11]:
data = pd.read_csv('https://raw.githubusercontent.com/esabunor/MLWorkspace/master/melb_data.csv')

In [12]:
#to_excel() — запись DataFrame в формат Excel-таблицы (.xlsx);
#to_json() — запись DataFrame в формат JSON (.json);
#to_xml() — запись DataFrame в формат XML-документа (.xml);
#to_sql() — запись DataFrame в базу данных SQL 
# (для реализации этого метода необходимо установить соединение с базой данных).

#read_excel() — чтение из формата Excel-таблицы (.xlsx) в DataFrame;
#read_json() — чтение из формата JSON (.json) в DataFrame;
#read_xml() — чтение из формата XML-документа (.xml) в DataFrame;
#read_sql() — чтение из базы данных SQL в DataFrame (также необходимо установить соединение с базой данных).

In [13]:
melb_data = pd.read_csv('data/melb_data.csv', sep=',')
# обращение к значению строки и столбца
melb_data.loc[15, 'Price']

np.float64(1310000.0)

In [14]:
# Вывод первых и последних строк
display(melb_data.head(3))
melb_data.tail(2)

,index,Suburb,Address,Rooms,Type,Price,Method,SellerG,Date,Distance,...,Car,Landsize,BuildingArea,YearBuilt,CouncilArea,Lattitude,Longtitude,Regionname,Propertycount,Coordinates
0,0,Abbotsford,85 Turner St,2,h,1480000.0,S,Biggin,3/12/2016,2.5,...,1.0,202.0,126.0,1970.0,Yarra,-37.7996,144.9984,Northern Metropolitan,4019.0,"-37.7996, 144.9984"
1,1,Abbotsford,25 Bloomburg St,2,h,1035000.0,S,Biggin,4/02/2016,2.5,...,0.0,156.0,79.0,1900.0,Yarra,-37.8079,144.9934,Northern Metropolitan,4019.0,"-37.8079, 144.9934"
2,2,Abbotsford,5 Charles St,3,h,1465000.0,SP,Biggin,4/03/2017,2.5,...,0.0,134.0,150.0,1900.0,Yarra,-37.8093,144.9944,Northern Metropolitan,4019.0,"-37.8093, 144.9944"

,index,Suburb,Address,Rooms,Type,Price,Method,SellerG,Date,Distance,...,Car,Landsize,BuildingArea,YearBuilt,CouncilArea,Lattitude,Longtitude,Regionname,Propertycount,Coordinates
13578,13578,Williamstown,96 Verdon St,4,h,2500000.0,PI,Sweeney,26/08/2017,6.8,...,5.0,866.0,157.0,1920.0,NaN,-37.85908,144.89299,Western Metropolitan,6380.0,"-37.85908, 144.89299"
13579,13579,Yarraville,6 Agnes St,4,h,1285000.0,SP,Village,26/08/2017,6.3,...,1.0,362.0,112.0,1920.0,NaN,-37.81188,144.88449,Western Metropolitan,6543.0,"-37.81188, 144.88449"

In [15]:
# размер таблицы — количество строк и количество столбцов
melb_data.shape

(13580, 23)

In [16]:
# Получение информации о столбцах
melb_data.info()

<class 'pandas.DataFrame'>
RangeIndex: 13580 entries, 0 to 13579
Data columns (total 23 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   index          13580 non-null  int64
 1   Suburb         13580 non-null  str
 2   Address        13580 non-null  str
 3   Rooms          13580 non-null  int64
 4   Type           13580 non-null  str
 5   Price          13580 non-null  float64
 6   Method         13580 non-null  str
 7   SellerG        13580 non-null  str
 8   Date           13580 non-null  str
 9   Distance       13580 non-null  float64
 10  Postcode       13580 non-null  int64
 11  Bedroom        13580 non-null  float64
 12  Bathroom       13580 non-null  float64
 13  Car            13580 non-null  float64
 14  Landsize       13580 non-null  float64
 15  BuildingArea   13580 non-null  float64
 16  YearBuilt      13580 non-null  float64
 17  CouncilArea    12211 non-null  str
 18  Lattitude      13580 non-null  float64
 19  Longtitude     13580 non-null  float64
 20  Regionname     13580 non-null  str
 21  Propertycount  13580 non-null  float64
 22  Coordinates    13580 non-null  str
dtypes: float64(11), int64(3), str(9)
memory usage: 2.4 MB

In [17]:
# Изменение типа данных в столбце
melb_data['Car'] = melb_data['Car'].astype('int64')

In [18]:
# Получение описательной статистики
melb_data.describe().loc[:, ['Distance', 'BuildingArea' , 'Price']]
#  С помощью параметра include можно указать тип данных, для которого нужно вывести описательную информацию.
melb_data.describe(include=['object'])

C:\Users\1\AppData\Local\Temp\ipykernel_7280\3800586421.py:4: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  melb_data.describe(include=['object'])

,Suburb,Address,Type,Method,SellerG,Date,CouncilArea,Regionname,Coordinates
count,13580,13580,13580,13580,13580,13580,12211,13580,13580
unique,314,13378,3,5,268,58,33,8,13097
top,Reservoir,5 Charles St,h,S,Nelson,27/05/2017,Moreland,Southern Metropolitan,"-37.8361, 144.9966"
freq,359,3,9449,9022,1565,473,1163,4695,12

In [19]:
# Получение частоты уникальных значений в столбце
# Для того чтобы определить, сколько раз в столбце повторяется каждый из вариантов значений 
# (т.е. найти частоту для каждого уникального знания),используется метод value_counts().
melb_data['Regionname'].value_counts()

Regionname
Southern Metropolitan         4695
Northern Metropolitan         3890
Western Metropolitan          2948
Eastern Metropolitan          1471
South-Eastern Metropolitan     450
Eastern Victoria                53
Northern Victoria               41
Western Victoria                32
Name: count, dtype: int64

In [20]:
melb_data['Regionname'].value_counts(normalize=True)

Regionname
Southern Metropolitan         0.345729
Northern Metropolitan         0.286451
Western Metropolitan          0.217084
Eastern Metropolitan          0.108321
South-Eastern Metropolitan    0.033137
Eastern Victoria              0.003903
Northern Victoria             0.003019
Western Victoria              0.002356
Name: proportion, dtype: float64

Агрегирующие методы

In [21]:
# Вычислим среднюю цену на объекты недвижимости:
print(melb_data['Price'].mean())
# Найдём максимальное количество парковочных мест:
print(melb_data['Car'].max())
# Медианное значение размера участков:
print(melb_data['Landsize'].median())
# Cтатический показатель моды — самого распространённого значения в столбце
print(melb_data['Rooms'].mode())
# стандартное отклонение (разброс) расстояния от центра города до объекта недвижимости
print(melb_data['Distance'].std())

1075684.079455081
10
440.0
0    3
Name: Rooms, dtype: int64
5.86872494307171

Фильтрация данных в DataFrame

In [22]:
mask = melb_data['Price'] > 2000000
display(melb_data[mask].head(2))
#Найдём количество зданий с тремя комнатами. Для этого отфильтруем таблицу по условию: 
# обратимся к результирующей таблице по столбцу Rooms и найдём число строк в ней с помощью атрибута shape:
melb_data[melb_data['Rooms'] == 3].shape[0]

,index,Suburb,Address,Rooms,Type,Price,Method,SellerG,Date,Distance,...,Car,Landsize,BuildingArea,YearBuilt,CouncilArea,Lattitude,Longtitude,Regionname,Propertycount,Coordinates
80,80,Albert Park,112 Beaconsfield Pde,3,h,2850000.0,PI,Buxton,4/03/2017,3.3,...,0,211.0,198.0,1890.0,Port Phillip,-37.8481,144.9499,Southern Metropolitan,3280.0,"-37.8481, 144.9499"
85,85,Albert Park,104 Richardson St,4,h,2300000.0,S,Marshall,7/05/2016,3.3,...,1,153.0,180.0,1880.0,Port Phillip,-37.8447,144.9523,Southern Metropolitan,3280.0,"-37.8447, 144.9523"

5881

In [23]:
# Условия можно комбинировать, используя операторы & (логическое И) и | (логическое ИЛИ)
# найдём число трёхкомнатных домов с ценой менее 300 тысяч:
melb_data[(melb_data['Rooms'] == 3) & (melb_data['Price'] < 300000)].shape[0]
# дома с ценой менее 300 тысяч, у которых либо число комнат равно 3 либо площадь домов более 100 квадратных метров
melb_data[((melb_data['Rooms'] == 3) | (melb_data['BuildingArea'] > 100)) & (melb_data['Price'] < 300000)].shape[0]

68

In [24]:
#Фильтрацию часто сочетают со статистическими методами. 
# Давайте найдём максимальное количество комнат в таунхаусах. 
# Так как в результате фильтрации получается DataFrame, то обратимся к нему по столбцу Rooms 
# и найдём максимальное значение:
melb_data[melb_data['Type'] == 't']['Rooms'].max()
# найдём медианную площадь здания у объектов, чья цена выше средней
mean_price = melb_data['Price'].mean()
melb_data[melb_data['Price'] > mean_price]['BuildingArea'].median()

np.float64(126.0)

In [25]:
# Создание копии таблицы
melb_df = melb_data.copy()
# Удаление столбцов - метод drop():
#labels — порядковые номера или имена столбцов, которые подлежат удалению; 
# если их несколько, то передаётся список;
#axis — ось совершения операции, axis=0 — удаляются строки, axis=1 — удаляются столбцы;
#inplace — если параметр выставлен на True, происходит замена изначального DataFrame на новый, 
# при этом метод ничего не возвращает; если на False — возвращается копия DataFrame, 
# из которой удалены указанные строки (столбцы), при этом первоначальный DataFrame не изменяется; 
# по умолчанию параметр равен False.
melb_df = melb_df.drop(['index', 'Coordinates'], axis=1)

In [26]:
# Математические операции со столбцами
total_rooms = melb_df['Rooms'] + melb_df['Bedroom'] + melb_df['Bathroom']
# введём признак - СТОЛБЕЦ MeanRoomsArea, который соответствует средней площади одной комнаты для каждого объекта
melb_df['MeanRoomsArea'] = melb_df['BuildingArea'] / total_rooms

Формат datetime YYYY-MM-DD HH: MM: SS

In [27]:
# функция pd.to_datetime(). параметр dayfirst= True/False
melb_df['Date'] = pd.to_datetime(melb_df['Date'], dayfirst=True)

In [28]:
# Выделение атрибутов datetime с помощью специального аксессора dt
#date — дата;
#year, month, day — год, месяц, день;
#time — время;
#hour, minute, second — час, минута, секунда;
#dayofweek — номер дня недели, от 0 до 6, где 0 — понедельник, 6 — воскресенье;
#dayofyear — порядковый день года;
#quarter — квартал (интервал в три месяца).

years_sold = melb_df['Date'].dt.year
print(years_sold)
print('Min year sold:', years_sold.min())
print('Max year sold:', years_sold.max())
print('Mode year sold:', years_sold.mode()[0])

melb_df['MonthSale'] = melb_df['Date'].dt.month
melb_df['MonthSale'].value_counts(normalize=True)

0        2016
1        2016
2        2017
3        2017
4        2016
         ...
13575    2017
13576    2017
13577    2017
13578    2017
13579    2017
Name: Date, Length: 13580, dtype: int32
Min year sold: 2016
Max year sold: 2017
Mode year sold: 2017

MonthSale
5     0.149411
7     0.145950
9     0.135862
6     0.134757
8     0.114138
11    0.082032
4     0.069882
3     0.049926
12    0.044698
10    0.040574
2     0.032622
1     0.000147
Name: proportion, dtype: float64

In [29]:
# Работа с интервалами
delta_days = melb_df['Date'] - pd.to_datetime('2016-01-01') 
# данные такого формата относятся к типу timedelta
display(delta_days.dt.days)

# Cоздадим признак возраста объекта недвижимости в годах на момент продажи. 
# Для этого выделим из столбца с датой продажи год и вычтем из него год постройки здания. 
# Результат оформим в виде столбца AgeBuilding:
melb_df['AgeBuilding'] = melb_df['Date'].dt.year - melb_df['YearBuilt']

0        337
1         34
2        428
3        428
4        155
        ...
13575    603
13576    603
13577    603
13578    603
13579    603
Name: Date, Length: 13580, dtype: int64

Тип данных Category

In [30]:
# Давайте определим число уникальных категорий в каждом столбце нашей таблицы melb_df. 
# Для этого создадим вспомогательную таблицу unique_counts:
# создаём пустой список
unique_list = []
# пробегаемся по именам столбцов в таблице
for col in melb_df.columns:
    # создаём кортеж (имя столбца, число уникальных значений)
    item = (col, melb_df[col].nunique(),melb_df[col].dtypes) 
    # добавляем кортеж в список
    unique_list.append(item) 
# создаём вспомогательную таблицу и сортируем её
unique_counts = pd.DataFrame(
    unique_list,
    columns=['Column_Name', 'Num_Unique', 'Type']
).sort_values(by='Num_Unique',  ignore_index=True)
# выводим её на экран
#display(unique_counts)

In [31]:
# Cпециальный тип данных — category. Этот тип данных является гибридным: 
# внешне он выглядит как строка, но внутренне представлен массивом целых чисел.

cols_to_exclude = ['Date', 'Rooms', 'Bedroom', 'Bathroom', 'Car'] # список столбцов, которые мы не берём во внимание
max_unique_count = 150 # задаём максимальное число уникальных категорий
for col in melb_df.columns: # цикл по именам столбцов
    if melb_df[col].nunique() < max_unique_count and col not in cols_to_exclude: # проверяем условие
        melb_df[col] = melb_df[col].astype('category') # преобразуем тип столбца
#display(melb_df.info())

In [32]:
# У типа данных category есть свой специальный аксесcор cat
print(melb_df['Regionname'].cat.categories)

# посмотрим, каким образом столбец кодируется в виде чисел в памяти компьютера. 
# Для этого можно воспользоваться атрибутом codes
display(melb_df['Regionname'].cat.codes)

# С помощью метода аксессора rename_categories() можно легко переименовать текущие значения категорий. 
# Для этого в данный метод нужно передать словарь, ключи которого — старые имена категорий, а значения — новые.
melb_df['Type'] = melb_df['Type'].cat.rename_categories({
    'u': 'unit',
    't': 'townhouse',
    'h': 'house'
})
display(melb_df['Type'])

# Можно добавить категорию flat в столбец Type с помощью метода акссесора cat add_categories(), 
# в который достаточно просто передать имя новой категории:
melb_df['Type'] = melb_df['Type'].cat.add_categories('flat')
new_houses_types = pd.Series(['unit', 'house', 'flat', 'flat', 'house'])
new_houses_types = new_houses_types.astype(melb_df['Type'].dtype)
display(new_houses_types)

Index(['Eastern Metropolitan', 'Eastern Victoria', 'Northern Metropolitan',
       'Northern Victoria', 'South-Eastern Metropolitan',
       'Southern Metropolitan', 'Western Metropolitan', 'Western Victoria'],
      dtype='str')

0        2
1        2
2        2
3        2
4        2
        ..
13575    4
13576    6
13577    6
13578    6
13579    6
Length: 13580, dtype: int8

0        house
1        house
2        house
3        house
4        house
         ...
13575    house
13576    house
13577    house
13578    house
13579    house
Name: Type, Length: 13580, dtype: category
Categories (3, str): ['house', 'townhouse', 'unit']

0     unit
1    house
2     flat
3     flat
4    house
dtype: category
Categories (4, str): ['house', 'townhouse', 'unit', 'flat']

In [33]:
melb_df['Suburb'].value_counts()
popular_suburb =melb_df['Suburb'].value_counts().nlargest(119).index
print(popular_suburb)
melb_df['Suburb'] = melb_df['Suburb'].apply(lambda x: x if x in popular_suburb else 'other')
display(melb_df['Suburb'])

Index(['Reservoir', 'Richmond', 'Bentleigh East', 'Preston', 'Brunswick',
       'Essendon', 'South Yarra', 'Glen Iris', 'Hawthorn', 'Coburg',
       ...
       'Doncaster East', 'Sunbury', 'Hoppers Crossing', 'Bundoora',
       'Greensborough', 'Caulfield North', 'Chadstone', 'Hughesdale',
       'Alphington', 'Middle Park'],
      dtype='str', name='Suburb', length=119)

0          Abbotsford
1          Abbotsford
2          Abbotsford
3          Abbotsford
4          Abbotsford
             ...
13575           other
13576    Williamstown
13577    Williamstown
13578    Williamstown
13579      Yarraville
Name: Suburb, Length: 13580, dtype: str

Создание и преобразование столбцов с помощью функций

In [34]:
# количество уникальных значений в столбце с помощью метода nunique()
print(melb_df['Address'].nunique())

13378

In [35]:
# Чтобы применить функцию к столбцу таблицы - передадим функцию function в аргумент метода столбца apply(). 
# В результате получим объект Series, который положим в переменную? с которой можно дальше работать
street_types = melb_df['Address'].apply(get_street_type)
# функция пишется для одного элемента столбца, а метод apply() применяется к каждому его элементу. 
# Используемая функция обязательно должна иметь возвращаемое значение.

# распространённый метод уменьшения количества уникальных категорий — выделим n подтипов, 
# которые встречаются чаще всего, а остальные обозначим как 'other' (другие)
popular_stypes =street_types.value_counts().nlargest(10).index
melb_df['StreetType'] = street_types.apply(lambda x: x if x in popular_stypes else 'other')

NameError: name 'get_street_type' is not defined

Сортировка данных в DataFrame

In [ ]:
# Основные параметры метода sort_values():
# by — имя или список имён столбцов, по значениям которых производится сортировка.
# axis — ось, по которой производится сортировка (0 — строки, 1 — столбцы). По умолчанию сортировка 
# производится по строкам.
# ascending — сортировка по возрастанию (от меньшего к большему). По умолчанию параметр выставлен на True, 
# для сортировки по убыванию (от большего к меньшему) необходимо выставить его на False.
#ignore_index — создаются ли новые индексы в таблице. По умолчанию выставлен на False и 
# сохраняет индексы изначальной таблицы.
#inplace — производится ли замена исходной таблицы на отсортированную. 
# По умолчанию параметр выставлен на False, то есть замены не производится. 
# Чтобы переопределить исходную таблицу на отсортированную, необходимо выставить этот параметр на True.

# Сортировка по значениям одного столбца
melb_df.sort_values(by='Price').head(5)
melb_df.sort_values(by='Date', ascending=False)

,Suburb,Address,Rooms,Type,Price,Method,SellerG,Date,Distance,Postcode,...,BuildingArea,YearBuilt,CouncilArea,Lattitude,Longtitude,Regionname,Propertycount,MeanRoomsArea,MonthSale,AgeBuilding
13120,other,12 Merricks St,3,house,575500.0,S,Barry,2017-09-23,14.0,3047,...,126.0,1970.0,NaN,-37.67980,144.90936,Northern Metropolitan,4294.0,18.000000,9,47.0
13240,other,12 Brookland Ct,4,house,1080000.0,S,Ray,2017-09-23,18.8,3170,...,204.0,1980.0,NaN,-37.93173,145.19475,South-Eastern Metropolitan,7113.0,20.400000,9,37.0
13242,other,5 Lola St,5,house,880000.0,PI,SN,2017-09-23,18.8,3170,...,126.0,1960.0,NaN,-37.92914,145.17372,South-Eastern Metropolitan,7113.0,9.692308,9,57.0
13243,other,25 Rupert Dr,3,house,840000.0,S,Ray,2017-09-23,18.8,3170,...,107.0,1972.0,NaN,-37.93271,145.17792,South-Eastern Metropolitan,7113.0,15.285714,9,45.0
13244,Murrumbeena,21 Reid St,3,house,1321188.0,SP,Woodards,2017-09-23,10.1,3163,...,200.0,1945.0,NaN,-37.90584,145.07250,Southern Metropolitan,4442.0,28.571429,9,72.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2347,Essendon,2/96 Cooper St,3,house,911000.0,S,Rendina,2016-02-04,8.0,3040,...,98.0,2008.0,Moonee Valley,-37.74540,144.89870,Western Metropolitan,9264.0,12.250000,2,8.0
1,Abbotsford,25 Bloomburg St,2,house,1035000.0,S,Biggin,2016-02-04,2.5,3067,...,79.0,1900.0,Yarra,-37.80790,144.99340,Northern Metropolitan,4019.0,15.800000,2,116.0
4544,Oakleigh South,4 Montrose St,4,house,876000.0,S,Buxton,2016-02-04,14.7,3167,...,126.0,1970.0,Kingston,-37.93840,145.08780,South-Eastern Metropolitan,3692.0,12.600000,2,46.0
6184,Surrey Hills,999A Riversdale Rd,3,house,1205000.0,S,Fletchers,2016-01-28,11.2,3127,...,126.0,1970.0,Whitehorse,-37.83610,145.10060,Southern Metropolitan,5457.0,18.000000,1,46.0
6183,Surrey Hills,1/10 Florence Rd,2,unit,813000.0,S,Fletchers,2016-01-28,11.2,3127,...,126.0,1970.0,Whitehorse,-37.82760,145.10230,Southern Metropolitan,5457.0,25.200000,1,46.0

In [36]:
# Сортировка по значениям нескольких столбцов
melb_df.sort_values(by=['Distance', 'Price'], ignore_index =True).loc[::10, ['Distance', 'Price']]

       Distance      Price
0           0.0   387000.0
10          0.7   600000.0
20          1.2   485000.0
30          1.2   595000.0
40          1.2   740000.0
...         ...        ...
13530      38.0   680000.0
13540      38.0   810000.0
13550      38.0  1155000.0
13560      41.0   650000.0
13570      45.9   650000.0

[1358 rows x 2 columns]

In [ ]:
# Комбинирование сортировки с фильтрацией
mask1 = melb_df['AreaRatio'] < -0.8
mask2 = melb_df['Type'] == 'townhouse'
mask3 = melb_df['SellerG'] == 'McGrath'
melb_df[mask1 & mask2 & mask3].sort_values(
    by=['Date', 'AreaRatio'],
    ascending=[True, False],
    ignore_index=True
).loc[:, ['Date', 'AreaRatio']]

Группировка данных в DataFrame

In [ ]:
# Метод groupby():
#by — имя или список имён столбцов, по которым производится группировка.
#axis — ось, по которой производится группировка (0 — строки, 1 — столбцы). 
# По умолчанию группировка производится по строкам.
#as_index — добавляется ли дополнительный индекс к таблице. По умолчанию установлен на True.

#Сначала мы разделяем данные на группы с помощью метода groupby(), 
# после чего к каждой группе применяем агрегацию и объединяем результаты в новую таблицу.
melb_df.groupby(by='Type').mean(numeric_only=True)
# сравним средние цены на объекты в зависимости от их типа:
melb_df.groupby('Type')['Price'].mean()

Type
house        1.242665e+06
townhouse    9.337351e+05
unit         6.051275e+05
Name: Price, dtype: float64

In [ ]:
# минимальное значение расстояния от центра города до объекта в зависимости от его региона. 
# Результат отсортируем по убыванию расстояния:
melb_df.groupby('Regionname')['Distance'].min().sort_values(ascending=False)

Regionname
Western Victoria              29.8
Eastern Victoria              25.2
Northern Victoria             21.8
South-Eastern Metropolitan    14.7
Eastern Metropolitan           7.8
Western Metropolitan           4.3
Southern Metropolitan          0.7
Northern Metropolitan          0.0
Name: Distance, dtype: float64

In [ ]:
# Группировка данных по одному критерию с несколькими агрегациями
melb_df.groupby('MonthSale')['Price'].agg(
    ['count', 'mean', 'max']
).sort_values(by='count', ascending=False)

           count          mean        max
MonthSale
5           2029  1.095086e+06  8000000.0
7           1982  8.995594e+05  9000000.0
9           1845  1.133612e+06  6400000.0
6           1830  1.076351e+06  7650000.0
8           1550  1.140499e+06  6500000.0
11          1114  1.117513e+06  5700000.0
4            949  1.018167e+06  5800000.0
3            678  1.141256e+06  5500000.0
12           607  1.170918e+06  5500000.0
10           551  1.065341e+06  6250000.0
2            443  1.104372e+06  4735000.0
1              2  1.009000e+06  1205000.0

In [ ]:
# Если вам нужна полная информация обо всех основных статистических характеристиках внутри каждой группы, 
# вы можете воспользоваться методом agg(), передав в качестве его параметра строку 'describe':
melb_df.groupby('MonthSale')['Price'].agg('describe')

,count,mean,std,min,25%,50%,75%,max
MonthSale,,,,,,,,
1,2.0,1.009000e+06,277185.858225,813000.0,911000.0,1009000.0,1107000.0,1205000.0
2,443.0,1.104372e+06,635973.074833,131000.0,690500.0,955000.0,1400500.0,4735000.0
3,678.0,1.141256e+06,682724.601038,210000.0,671750.0,946000.0,1429722.0,5500000.0
4,949.0,1.018167e+06,567481.377534,160000.0,641000.0,900000.0,1255000.0,5800000.0
5,2029.0,1.095086e+06,657317.760843,145000.0,647000.0,911982.0,1385000.0,8000000.0
6,1830.0,1.076351e+06,625976.795502,145000.0,670000.0,890750.0,1323750.0,7650000.0
7,1982.0,8.995594e+05,513444.182441,170000.0,580000.0,773500.0,1070000.0,9000000.0
8,1550.0,1.140499e+06,668166.765540,185000.0,670000.0,965000.0,1400000.0,6500000.0
9,1845.0,1.133612e+06,637902.861826,85000.0,700000.0,970000.0,1385000.0,6400000.0
10,551.0,1.065341e+06,619817.457990,270000.0,642500.0,920000.0,1329000.0,6250000.0
11,1114.0,1.117513e+06,697693.159730,240000.0,655500.0,923000.0,1380000.0,5700000.0
12,607.0,1.170918e+06,761332.384103,275000.0,660000.0,960000.0,1418500.0,5500000.0

In [37]:
melb_df.groupby('Regionname')['SellerG'].agg(['nunique',set])

,nunique,set
Regionname,,
Eastern Metropolitan,70,"{Changing, Fletchers, Harcourts, Mason, Buxton..."
Eastern Victoria,18,"{Fletchers, Harcourts, Peake, Eview, McGrath, ..."
Northern Metropolitan,112,"{Fletchers, Hodges, buyMyplace, Philip, iTRAK,..."
Northern Victoria,16,"{McGrath, LITTLE, Barry, Keatings, Mason, YPA,..."
South-Eastern Metropolitan,52,"{Fletchers, Rexhepi, Harcourts, Hodges, Buxton..."
Southern Metropolitan,131,"{Fletchers, Hodges, Weast, buyMyplace, Lucas, ..."
Western Metropolitan,92,"{McNaughton, Hodges, Homes, Dingle, Douglas, C..."
Western Victoria,9,"{YPA, Ryder, hockingstuart, FN, Raine, Relianc..."

Сводные таблицы

In [ ]:
# мы уже умеем строить таблицу, которая показывает зависимость медианной цены и площади здания от числа комнат:
melb_df.groupby('Rooms')[['Price', 'BuildingArea']].median()

           Price  BuildingArea
Rooms
1       385000.0         107.0
2       690000.0         126.0
3       950000.0         126.0
4      1285000.0         142.0
5      1660000.0         176.0
6      1800000.0         126.0
7      1496000.0         216.5
8      1515000.0         126.0
10      900000.0         126.0

In [ ]:
# Также можно построить таблицу, в которой мы будем учитывать не только число комнат, но и тип здания (Type). 
# Для этого в параметрах метода groupby() укажем список из нескольких интересующих нас столбцов.
melb_df.groupby(['Rooms', 'Type'])['Price'].mean()

Rooms  Type
1      house        8.668655e+05
       townhouse    5.927045e+05
       unit         3.899289e+05
2      house        1.017238e+06
       townhouse    7.101585e+05
       unit         6.104905e+05
3      house        1.109233e+06
       townhouse    9.847087e+05
       unit         8.505963e+05
4      house        1.462283e+06
       townhouse    1.217092e+06
       unit         1.037476e+06
5      house        1.877327e+06
       townhouse    1.035000e+06
6      house        1.869508e+06
       unit         5.200000e+05
7      house        1.920700e+06
8      house        1.510286e+06
       unit         2.250000e+06
10     house        9.000000e+05
Name: Price, dtype: float64

In [ ]:
# Такая организация индексов называется иерархической
# Для того, чтобы финальный результат был представлен в виде сводной таблицы 
# (первый группировочный признак по строкам, а второй — по столбцам), а не в виде Series 
# с иерархическими индексами, к результату чаще всего применяют метод **unstack()**, 
# который позволяет переопределить вложенный индекс в виде столбцов таблицы:
melb_df.groupby(['Rooms', 'Type'])['Price'].mean().unstack()

Type          house     townhouse          unit
Rooms
1      8.668655e+05  5.927045e+05  3.899289e+05
2      1.017238e+06  7.101585e+05  6.104905e+05
3      1.109233e+06  9.847087e+05  8.505963e+05
4      1.462283e+06  1.217092e+06  1.037476e+06
5      1.877327e+06  1.035000e+06           NaN
6      1.869508e+06           NaN  5.200000e+05
7      1.920700e+06           NaN           NaN
8      1.510286e+06           NaN  2.250000e+06
10     9.000000e+05           NaN           NaN

In [ ]:
# Метод pivot_table для построения сводных таблиц
* ```values``` — имя столбца, по которому необходимо получить сводные данные, применяя агрегирующую функцию;
* ```index``` — имя столбца, значения которого станут строками сводной таблицы;
* ```columns``` — имя столбца, значения которого станут столбцами сводной таблицы;
* ```aggfunc``` — имя или список имён агрегирующих функций (по умолчанию — подсчёт среднего, 'mean');
* ```fill_value``` — значение, которым необходимо заполнить пропуски (по умолчанию пропуски не заполняются).

In [ ]:
melb_df.pivot_table(
    values='Price',
    index='Rooms',
    columns='Type',
    fill_value=0
).round()

Type       house  townhouse       unit
Rooms
1       866866.0   592705.0   389929.0
2      1017238.0   710158.0   610491.0
3      1109233.0   984709.0   850596.0
4      1462283.0  1217092.0  1037476.0
5      1877327.0  1035000.0        0.0
6      1869508.0        0.0   520000.0
7      1920700.0        0.0        0.0
8      1510286.0        0.0  2250000.0
10      900000.0        0.0        0.0

In [ ]:
melb_df.pivot_table(
    values='Landsize',
    index='Regionname',
    columns='Type',
    aggfunc=['median', 'mean'],
    fill_value=0
)

                           median                          mean              \
Type                        house townhouse   unit        house   townhouse
Regionname
Eastern Metropolitan        674.0     233.5  203.0   717.422847  269.440678
Eastern Victoria            843.0       0.0  230.0  3108.960000    0.000000
Northern Metropolitan       459.5     134.0    0.0   619.249092  317.325733
Northern Victoria           724.0       0.0    0.0  3355.463415    0.000000
South-Eastern Metropolitan  630.5     240.0  199.0   664.306701  212.160000
Southern Metropolitan       586.0     246.0    0.0   569.643881  278.858824
Western Metropolitan        531.0     198.0   62.0   507.883406  244.560669
Western Victoria            599.5       0.0    0.0   655.500000    0.000000


Type                              unit
Regionname
Eastern Metropolitan        330.444444
Eastern Victoria            295.333333
Northern Metropolitan       495.026538
Northern Victoria             0.000000
South-Eastern Metropolitan  357.864865
Southern Metropolitan       466.380245
Western Metropolitan        557.637232
Western Victoria              0.000000

In [ ]:
# Многомерные сводные таблицы
# Для того чтобы исследовать зависимость от большего числа признаков, 
# можно передать список признаков в параметр index или параметр columns

#Давайте построим таблицу, в которой по индексам будут располагаться признаки метода продажи (Method) 
# и типа объекта (Type), по столбцам — наименование региона (Regionname), а на пересечении строк и столбцов 
# будет стоять медианная цена объекта (Price)
melb_df.pivot_table(
    values='Price',
    index=['Method','Type'],
    columns='Regionname',
    aggfunc='median',
    fill_value=0
)

Regionname        Eastern Metropolitan  Eastern Victoria  \
Method Type
PI     house                 1244000.0          780000.0
       townhouse              760000.0               0.0
       unit                   650000.0               0.0
S      house                 1127000.0          675000.0
       townhouse              828000.0               0.0
       unit                   645750.0          492000.0
SA     house                  932500.0          950000.0
       townhouse              807500.0               0.0
       unit                        0.0               0.0
SP     house                 1050000.0          672500.0
       townhouse              910000.0               0.0
       unit                   515000.0          400000.0
VB     house                 1100000.0          712500.0
       townhouse              892500.0               0.0
       unit                   500000.0               0.0

Regionname        Northern Metropolitan  Northern Victoria  \
Method Type
PI     house                   900000.0           500000.0
       townhouse               632500.0                0.0
       unit                    410000.0                0.0
S      house                   920000.0           555000.0
       townhouse               750000.0                0.0
       unit                    525500.0                0.0
SA     house                   817500.0           540000.0
       townhouse               425000.0                0.0
       unit                    616000.0                0.0
SP     house                   900000.0           521000.0
       townhouse               690000.0                0.0
       unit                    470000.0                0.0
VB     house                  1050000.0           690000.0
       townhouse               640000.0                0.0
       unit                    450000.0                0.0

Regionname        South-Eastern Metropolitan  Southern Metropolitan  \
Method Type
PI     house                        865000.0              1725000.0
       townhouse                   1190000.0              1055000.0
       unit                         525000.0               571250.0
S      house                        883300.0              1611000.0
       townhouse                    875000.0              1135000.0
       unit                         606000.0               655000.0
SA     house                        880000.0              1390000.0
       townhouse                         0.0              1141000.0
       unit                              0.0               580000.0
SP     house                        770000.0              1521750.0
       townhouse                    800000.0              1162500.0
       unit                         601000.0               550000.0
VB     house                        850000.0              1800000.0
       townhouse                         0.0              1250000.0
       unit                         700000.0               500000.0

Regionname        Western Metropolitan  Western Victoria
Method Type
PI     house                  870000.0          630000.0
       townhouse              670000.0               0.0
       unit                   360000.0               0.0
S      house                  870000.0          397500.0
       townhouse              729000.0               0.0
       unit                   489000.0               0.0
SA     house                  772500.0               0.0
       townhouse              467500.0               0.0
       unit                   571000.0               0.0
SP     house                  865000.0          360000.0
       townhouse              702500.0               0.0
       unit                   460000.0               0.0
VB     house                  880000.0               0.0
       townhouse              689500.0               0.0
       unit                   420000.0               0.0

Доступ к данным в сводной таблице

In [ ]:
pivot = melb_df.pivot_table(
    values='Landsize',
    index='Regionname',
    columns='Type',
    aggfunc=['median', 'mean'],
    fill_value=0
)
#Выведем её столбцы с помощью атрибута columns:
pivot.columns

MultiIndex([('median',     'house'),
            ('median', 'townhouse'),
            ('median',      'unit'),
            (  'mean',     'house'),
            (  'mean', 'townhouse'),
            (  'mean',      'unit')],
           names=[None, 'Type'])

In [ ]:
# из таблицы pivot мы можем получить средние значения площадей участков для типа здания unit, 
# просто последовательно обратившись по имени столбцов:
display(pivot['mean']['unit'])

Regionname
Eastern Metropolitan          330.444444
Eastern Victoria              295.333333
Northern Metropolitan         495.026538
Northern Victoria               0.000000
South-Eastern Metropolitan    357.864865
Southern Metropolitan         466.380245
Western Metropolitan          557.637232
Western Victoria                0.000000
Name: unit, dtype: float64

In [ ]:
# Аналогично производится и фильтрация данных. Например, если нам нужны регионы, 
# в которых средняя площадь здания для домов типа house меньше их медианной площади, 
# то мы можем найти их следующим образом:
mask = pivot['mean']['house'] < pivot['median']['house']
filtered_pivot = pivot[mask]
display(filtered_pivot)

                      median                        mean              \
Type                   house townhouse  unit       house   townhouse
Regionname
Southern Metropolitan  586.0     246.0   0.0  569.643881  278.858824
Western Metropolitan   531.0     198.0  62.0  507.883406  244.560669


Type                         unit
Regionname
Southern Metropolitan  466.380245
Western Metropolitan   557.637232

In [ ]:
# Чтобы получить индексы отфильтрованной таблицы, можно воспользоваться атрибутом index и 
# обернуть результат в список:
print(list(filtered_pivot.index))

['Southern Metropolitan', 'Western Metropolitan']

In [ ]:
movies = pd.read_csv('data/movies.csv', sep=',')
ratings1 = pd.read_csv('data/ratings1.csv', sep=',')
ratings2 = pd.read_csv('data/ratings2.csv', sep=',')
dates = pd.read_csv('data/dates.csv', sep=',')

Объединение DataFrame: concat

In [ ]:
# objs — список объектов DataFrame ([df1, df2,…]), которые должны быть сконкатенированы;
# axis— ось определяет направление конкатенации: 0 — конкатенация по строкам (по умолчанию), 
# 1 — конкатенация по столбцам;
# join— либо ```inner``` (пересечение), либо ```outer``` (объединение); 
# рассмотрим этот момент немного позже;
# ignore_index — по умолчанию установлено значение False, которое позволяет значениям индекса 
# оставаться такими, какими они были в исходных данных. Если установлено значение True, 
# параметр будет игнорировать исходные значения и повторно назначать значения индекса в последовательном порядке.

ratings = pd.concat(
    [ratings1, ratings2],
    ignore_index=True
)

# Чтобы очистить таблицу от дублей, мы можем воспользоваться методом DataFrame drop_duplicates(), 
# который удаляет повторяющиеся строки в таблице. Не забываем обновить индексы после удаления дублей, 
# выставив параметр ignore_index в методе drop_duplicates() на значение True:
ratings = ratings.drop_duplicates(ignore_index=True)
print('Число строк в таблице ratings: ', ratings.shape[0])

Число строк в таблице ratings:  100836

In [ ]:
# конкатенируем таблицы ratings и dates по столбцам:
ratings_dates = pd.concat([ratings, dates], axis=1)
display(ratings_dates.tail(4))

        userId  movieId  rating                 date
100832     610   168248     5.0  2017-05-03 22:21:31
100833     610   168250     5.0  2017-05-08 19:50:47
100834     610   168252     5.0  2017-05-03 21:19:12
100835     610   170875     3.0  2017-05-03 21:20:15

Типы объединений

In [ ]:
# *inner* (внутреннее)
# *outer* (внешнее) 3 типа:
# ```full``` — используется как outer по умолчанию, объединяет все варианты в обеих таблицах
# ```left```
# ```right```

In [ ]:
# Метод объединения join
# ```other``` — таблица, которую мы присоединяем. При объединении она является «правой», 
# а исходная таблица, от имени которой вызывается метод, является «левой».
# ```how``` — параметр типа объединения. Он может принимать значения 
# 'inner', 'left' (left outer), 'right' (right outer), и 'outer' (full outer). 
# По умолчанию параметр установлен на 'left'.
# ```on``` — параметр, который определяет, по какому столбцу в «левой» таблице происходит объединение 
# по индексам из «правой».
# ```lsuffix``` и ```rsuffix``` — дополнения (суффиксы) к названиям одноимённых столбцов в «левой» и «правой» таблицах.
joined = ratings_dates.join(
    movies.set_index('movieId'),
    on='movieId',
    how='left'
)
display(joined.head())

,userId,movieId,rating,date,title,genres
0,1,1,4.0,2000-07-30 18:45:03,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
1,1,3,4.0,2000-07-30 18:20:47,Grumpier Old Men (1995),Comedy|Romance
2,1,6,4.0,2000-07-30 18:37:04,Heat (1995),Action|Crime|Thriller
3,1,47,5.0,2000-07-30 19:03:35,Seven (a.k.a. Se7en) (1995),Mystery|Thriller
4,1,50,5.0,2000-07-30 18:48:51,"Usual Suspects, The (1995)",Crime|Mystery|Thriller

In [ ]:
# Метод объединения merge
# ```right``` — присоединяемая таблица. По умолчанию она является «правой».
# ```how``` — параметр типа объединения. По умолчанию принимает значение 'inner'.
# ```on``` — параметр, который определяет, по какому столбцу происходит объединение. 
# Определяется автоматически, но рекомендуется указывать вручную.
# ```left_on``` — если названия столбцов в «левой» и «правой» таблицах не совпадают, 
# то данный параметр отвечает за наименования ключевого столбца исходной таблицы.
# ```right_on``` — аналогично предыдущему, параметр отвечает за наименование ключевого столбца присоединяемой таблицы.
merged = ratings_dates.merge(
    movies,
    on='movieId',
    how='left'
)
display(merged.head())

,userId,movieId,rating,date,title,genres
0,1,1,4.0,2000-07-30 18:45:03,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
1,1,3,4.0,2000-07-30 18:20:47,Grumpier Old Men (1995),Comedy|Romance
2,1,6,4.0,2000-07-30 18:37:04,Heat (1995),Action|Crime|Thriller
3,1,47,5.0,2000-07-30 19:03:35,Seven (a.k.a. Se7en) (1995),Mystery|Thriller
4,1,50,5.0,2000-07-30 18:48:51,"Usual Suspects, The (1995)",Crime|Mystery|Thriller

In [ ]:
# объединим таблицы ratings1 и ratings2, как мы уже делали раньше, но теперь используем метод ```merge()```:
merge_ratings = ratings1.merge(ratings2, how='outer')
print('Число строк в таблице merge_ratings: ', merge_ratings.shape[0])
display(merge_ratings)

Число строк в таблице merge_ratings:  100836

        userId  movieId  rating
0            1        1     4.0
1            1        3     4.0
2            1        6     4.0
3            1       47     5.0
4            1       50     5.0
...        ...      ...     ...
100831     610   166534     4.0
100832     610   168248     5.0
100833     610   168250     5.0
100834     610   168252     5.0
100835     610   170875     3.0

[100836 rows x 3 columns]

In [ ]:
# при использовании метода merge() для склейки двух таблиц у нас автоматически пропали дубликаты, 
# которые мы видели при использовании метода concat(). 
# Это особенность метода merge() — автоматическое удаление дублей