In [7]:
import pandas as pd
pd.__version__
print(pd.__name__)

pandas

Задание 2.4

В аптеку поступают партии лекарств. Их названия находятся в списке names, количество единиц товара находится в списке counts.

Например:

names = ['chlorhexidine', 'cyntomycin', 'afobazol'] counts = [15, 18, 7]

Напишите функцию create_medications(names, counts), которая создает Series medications, индексами которой являются названия лекарств names, а значениями - их количество в поставке counts.

А также напишите функцию get_percent(medications, name), которая возвращает долю количества товара с именем name от общего количества товаров в поставке в процентах.

In [8]:
import pandas as pd
def create_medications(names, counts):
    medications = pd.Series(index=names, data=counts)
    return medications
def get_percent(medications, name):
    return(medications.loc[name]/sum(medications) * 100)

names=['chlorhexidine', 'cyntomycin', 'afobazol']
counts=[15, 18, 7]
medications = create_medications(names, counts)

print(get_percent(medications, "chlorhexidine")) #37.5

37.5

Задание 3.5

Вы работаете аналитиком в компании ScienceYou. Ваша задача — проанализировать чистую прибыль.

Доходы (income), расходы (expenses) и годы (years), соответствующие им, предоставлены вам в виде списков.

Создайте функцию create_companyDF(income, expenses, years), которая возвращает DataFrame, составленный из входных данных со столбцами Income и Expenses и индексами, соответствующими годам рассматриваемого периода.

Также напишите функцию get_profit(df, year), которая возвращает разницу между доходом и расходом, записанными в таблице df, за год year.

Примечание. Если информация за запрашиваемый год не указана в вашей таблице, вам необходимо вернуть None.

In [9]:
import pandas as pd

def create_companyDF(income, expenses, years):
    df = pd.DataFrame({
    'Income': income,
    'Expenses': expenses
    })
    df.index = years
    return df

def get_profit(df, year):
    if year in df.index:
        profit = (df.loc[year, 'Income'] - df.loc[year, 'Expenses'])
    else:
        profit = None
    return profit

income = [478, 512, 196]
expenses = [156, 130, 270]
years = [2018, 2019, 2020]

df = create_companyDF(income, expenses, years)

print(get_profit(df, 2018))

322

In [10]:
import pandas as pd

In [11]:
student_data = pd.read_csv('data/students_performance.csv', sep=',')
display(student_data)

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75
...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95
996,male,group C,high school,free/reduced,none,62,55,55
997,female,group C,high school,free/reduced,completed,59,71,65
998,female,group D,some college,standard,completed,68,78,77
999,female,group D,some college,free/reduced,none,77,86,86

gender — пол;

race/ethnicity — раса/этническая принадлежность;

parental level of education — уровень образования родителей;

lunch — какие обеды получал студент во время обучения (standard — платный, free/reduced — бесплатный);

test preparation course — посещал ли студент курсы подготовки к экзаменам (none — не посещал, completed — посещал);

math score, reading score, writing score — баллы по математике, чтению и письму по сто балльной шкале.

------

Каков балл по письму у студента под индексом 155?

In [12]:
print(student_data.loc[155,'writing score'])

88

Сколько суммарно пропущенных значений в таблице?

In [13]:
student_data.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 8 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   gender                       1000 non-null   str
 1   race/ethnicity               1000 non-null   str
 2   parental level of education  1000 non-null   str
 3   lunch                        1000 non-null   str
 4   test preparation course      1000 non-null   str
 5   math score                   1000 non-null   int64
 6   reading score                1000 non-null   int64
 7   writing score                1000 non-null   int64
dtypes: int64(3), str(5)
memory usage: 62.6 KB

Каков у студентов средний балл по математике?
Округлите ответ до целого числа.

In [14]:
student_data.describe()

       math score  reading score  writing score
count  1000.00000    1000.000000    1000.000000
mean     66.08900      69.169000      68.054000
std      15.16308      14.600192      15.195657
min       0.00000      17.000000      10.000000
25%      57.00000      59.000000      57.750000
50%      66.00000      70.000000      69.000000
75%      77.00000      79.000000      79.000000
max     100.00000     100.000000     100.000000

Какая расовая группа является самой крупной в учебном заведении?
В качестве ответа введите идентификатор группы (A, B, C, D, E).

In [15]:
student_data.describe(include=['object'])

C:\Users\1\AppData\Local\Temp\ipykernel_10932\3517839956.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  student_data.describe(include=['object'])

,gender,race/ethnicity,parental level of education,lunch,test preparation course
count,1000,1000,1000,1000,1000
unique,2,5,6,2,2
top,female,group C,some college,standard,none
freq,518,319,226,645,642

Каков средний балл по чтению у студентов, которые посещали курсы подготовки к экзаменам?
Округлите ответ до целого числа.

In [16]:
mask = student_data['test preparation course'] == 'completed'
student_data[mask]['reading score'].mean()

np.float64(73.89385474860335)

Сколько студентов получили 0 баллов по математике?

In [17]:
mask1 = student_data['math score'] == 0
student_data[mask1].shape[0]

1

Проверьте гипотезу: у студентов с оплачиваемым питанием средний балл по математике выше, чем у студентов с льготным питанием.
В качестве ответа напишите наибольший средний балл по математике среди этих групп студентов.
Округлите ответ до целого числа.

In [18]:
mask2 = student_data['lunch'] == 'standard'
mask3 = student_data['lunch'] == 'free/reduced'
student_data[mask2]['math score'].mean()

np.float64(70.03410852713178)

Каков процент студентов, родители которых имеют высшее образование уровня бакалавриата (bachelor's degree)?
Округлите ответ до целого числа.
Не указывайте знак %.

In [19]:
mask4 = student_data['parental level of education'] == "bachelor's degree"
res = student_data[mask4].shape[0] / 1000 * 100
print(res)

11.799999999999999

Насколько медианный балл по письму у студентов в расовой группе А отличается от среднего балла по письму у студентов в расовой группе C?
Округлите ответ до целого и запишите модуль этого числа.

In [20]:
a = student_data[student_data['race/ethnicity'] == 'group A']['writing score'].median()
b = student_data[student_data['race/ethnicity'] == 'group C']['writing score'].mean()
print(round(abs(a - b)))

6

Задан DataFrame customer_df, содержащий столбцы:
cust_id — идентификатор клиента;
cust_age — возраст клиента (точкой отсчёта возраста считается 2021 год);
cust_sale — персональная скидка клиента;
cust_year_birth — год рождения клиента;
cust_order — сумма заказа клиента.

In [21]:
customer_df = pd.DataFrame({
        'number': [0, 1, 2, 3, 4],
        'cust_id': [128, 1201, 9832, 4392, 7472],
        'cust_age': [13, 21, 19, 21, 60],
        'cust_sale': [0, 0, 0.2, 0.15, 0.3],
        'cust_year_birth': [2008, 2000, 2002, 2000, 1961],
        'cust_order': [1400, 14142, 900, 1240, 8430]
    })

In [22]:
display(customer_df)

   number  cust_id  cust_age  cust_sale  cust_year_birth  cust_order
0       0      128        13       0.00             2008        1400
1       1     1201        21       0.00             2000       14142
2       2     9832        19       0.20             2002         900
3       3     4392        21       0.15             2000        1240
4       4     7472        60       0.30             1961        8430

Напишите функцию delete_columns(df, col=[]), которая удаляет столбцы из DataFrame и возвращает новую таблицу. Если одного из указанных столбцов не существует в таблице, то функция должна возвращать None.

In [23]:
import pandas as pd
def delete_columns(df, col=[]):
    for cc in col:
        if cc not in df.columns:
            return None
    return df.drop(col, axis = 1)

test_df_1 = pd.DataFrame({
            'number': [0, 1, 2, 3, 4],
            'cust_id': [128, 1201, 9832, 4392, 7472],
            'cust_age': [13, 21, 19, 21, 60],
            'cust_sale': [0, 0, 0.2, 0.15, 0.3],
            'cust_year_birth': [2008, 2000, 2002, 2000, 1961],
            'cust_order': [1400, 14142, 900, 1240, 8430]
        })


print(delete_columns(col = ['cust_sale'], df = test_df_1))

   number  cust_id  cust_age  cust_year_birth  cust_order
0       0      128        13             2008        1400
1       1     1201        21             2000       14142
2       2     9832        19             2002         900
3       3     4392        21             2000        1240
4       4     7472        60             1961        8430

Задан DataFrame countries_df, содержащий следующие столбцы: название страны, население (population) в миллионах человек и площадь страны (area) в квадратных километрах.
Для каждой страны рассчитайте плотность населения (количество человек на квадратный километр).

Затем по полученным данным рассчитайте среднее по плотностям населения в указанных странах. Ответ округлите до сотых.

Плотность населения рассчитывается как количество человек, проживающих на территории отдельной страны, делённое на площадь этой страны. Обратите внимание, что население в таблице представлено в миллионах.

In [24]:
countries_df = pd.DataFrame({
    'country': ['Англия', 'Канада', 'США', 'Россия', 'Украина', 'Беларусь', 'Казахстан'],
    'population': [56.29, 38.05, 322.28, 146.24, 45.5, 9.5, 17.04],
    'area': [133396, 9984670, 9826630, 17125191, 603628, 207600, 2724902]
})
display(countries_df)

     country  population      area
0     Англия       56.29    133396
1     Канада       38.05   9984670
2        США      322.28   9826630
3     Россия      146.24  17125191
4    Украина       45.50    603628
5   Беларусь        9.50    207600
6  Казахстан       17.04   2724902

In [25]:
countries_df['dens'] = (countries_df['population'] *1e6) / countries_df['area']
res = countries_df['dens'].mean()
print(round(res,2))

84.93

In [26]:
import pandas as pd

Citi_Bike = pd.read_csv('data/citibike-tripdata.csv', sep=',')
Citi_Bike.head()

,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
0,2018-09-01 00:00:05.2690,2018-09-01 00:27:20.6340,252.0,MacDougal St & Washington Sq,40.732264,-73.998522,366.0,Clinton Ave & Myrtle Ave,40.693261,-73.968896,25577,Subscriber,1980,1
1,2018-09-01 00:00:11.2810,2018-09-01 00:02:23.4810,314.0,Cadman Plaza West & Montague St,40.693830,-73.990539,3242.0,Schermerhorn St & Court St,40.691029,-73.991834,34377,Subscriber,1969,0
2,2018-09-01 00:00:20.6490,2018-09-01 00:55:58.5470,3142.0,1 Ave & E 62 St,40.761227,-73.960940,3384.0,Smith St & 3 St,40.678724,-73.995991,30496,Subscriber,1975,1
3,2018-09-01 00:00:21.7460,2018-09-01 00:07:38.5830,308.0,St James Pl & Oliver St,40.713079,-73.998512,3690.0,Park Pl & Church St,40.713342,-74.009355,28866,Subscriber,1984,2
4,2018-09-01 00:00:27.3150,2018-09-01 02:21:25.3080,345.0,W 13 St & 6 Ave,40.736494,-73.997044,380.0,W 4 St & 7 Ave S,40.734011,-74.002939,20943,Customer,1994,1

In [27]:
Citi_Bike.info()

<class 'pandas.DataFrame'>
RangeIndex: 300000 entries, 0 to 299999
Data columns (total 14 columns):
 #   Column                   Non-Null Count   Dtype
---  ------                   --------------   -----
 0   starttime                300000 non-null  str
 1   stoptime                 300000 non-null  str
 2   start station id         299831 non-null  float64
 3   start station name       299831 non-null  str
 4   start station latitude   300000 non-null  float64
 5   start station longitude  300000 non-null  float64
 6   end station id           299831 non-null  float64
 7   end station name         299831 non-null  str
 8   end station latitude     300000 non-null  float64
 9   end station longitude    300000 non-null  float64
 10  bikeid                   300000 non-null  int64
 11  usertype                 300000 non-null  str
 12  birth year               300000 non-null  int64
 13  gender                   300000 non-null  int64
dtypes: float64(6), int64(3), str(5)
memory usage: 32.0 MB

Датасет представляет собой таблицу с информацией о 300 тысячах поездок за первые пять дней сентября 2018 года и включает в себя следующую информацию:

starttime — время начала поездки (дата, время);

stoptime — время окончания поездки (дата, время);

start station id — идентификатор стартовой стоянки;

start station name — название стартовой стоянки;

start station latitude, start station longitude — географическая широта и долгота стартовой стоянки;

end station id — идентификатор конечной стоянки;

end station name — название конечной стоянки;

end station latitude, end station longitude — географическая широта и долгота конечной стоянки;

bikeid — идентификатор велосипеда;

usertype — тип пользователя (Customer — клиент с подпиской на 24 часа или на три дня, Subscriber — подписчик с годовой арендой велосипеда);

birth year — год рождения клиента;

gender — пол клиента (0 — неизвестный, 1 — мужчина, 2 — женщина).

In [28]:
Citi_Bike['start station id'].mode()

0    281.0
Name: start station id, dtype: float64

In [29]:
Citi_Bike['bikeid'].mode()

0    33887
Name: bikeid, dtype: int64

In [30]:
Citi_Bike['usertype'].value_counts(normalize=True)

usertype
Subscriber    0.774007
Customer      0.225993
Name: proportion, dtype: float64

In [31]:
Citi_Bike['gender'].value_counts()

gender
1    183582
2     74506
0     41912
Name: count, dtype: int64

In [32]:
Citi_Bike['start station name'].value_counts().nunique

<bound method IndexOpsMixin.nunique of start station name
Grand Army Plaza & Central Park S    1928
Central Park S & 6 Ave               1909
Pershing Square North                1873
12 Ave & W 40 St                     1845
West St & Chambers St                1835
                                     ...
NYCBS Depot - GOW                      15
Franklin Ave & Empire Blvd             11
Railroad Ave & Kay Ave                  9
47 Ave & Skillman Ave                   7
Eastern Pkwy & Washington Ave           6
Name: count, Length: 759, dtype: int64>

In [33]:
Citi_Bike['end station name'].value_counts().nunique

<bound method IndexOpsMixin.nunique of end station name
West St & Chambers St          1963
12 Ave & W 40 St               1909
Pershing Square North          1850
Central Park S & 6 Ave         1828
E 17 St & Broadway             1804
                               ...
Exchange Place                    3
Union St                          1
Warren St                         1
Montrose Ave & Bushwick Ave       1
Liberty Light Rail                1
Name: count, Length: 765, dtype: int64>

In [34]:
Citi_Bike['birth year'].max()

np.int64(2002)

In [35]:
Citi_Bike['start station name'].min()

'1 Ave & E 110 St'

In [36]:
Citi_Bike['end station name'].max()

'Yankee Ferry Terminal'

In [37]:
Citi_Bike = Citi_Bike.drop(['start station id', 'end station id'], axis=1) 
Citi_Bike.info()

<class 'pandas.DataFrame'>
RangeIndex: 300000 entries, 0 to 299999
Data columns (total 12 columns):
 #   Column                   Non-Null Count   Dtype
---  ------                   --------------   -----
 0   starttime                300000 non-null  str
 1   stoptime                 300000 non-null  str
 2   start station name       299831 non-null  str
 3   start station latitude   300000 non-null  float64
 4   start station longitude  300000 non-null  float64
 5   end station name         299831 non-null  str
 6   end station latitude     300000 non-null  float64
 7   end station longitude    300000 non-null  float64
 8   bikeid                   300000 non-null  int64
 9   usertype                 300000 non-null  str
 10  birth year               300000 non-null  int64
 11  gender                   300000 non-null  int64
dtypes: float64(4), int64(3), str(5)
memory usage: 27.5 MB

Задание 6.9

Замените признак birth year на более понятный признак возраста клиента age. Годом отсчёта возраста выберите 2018 год. Столбец birth year удалите из таблицы. Сколько поездок совершено клиентами старше 60 лет?

In [38]:
import numpy as np
def age(year):
    res = abs(int(year) - 2018)
    return res

In [39]:
Citi_Bike['age'] = Citi_Bike['birth year'].apply(age)
display(Citi_Bike['age'])

0         38
1         49
2         43
3         34
4         24
          ..
299995    28
299996    36
299997    27
299998    43
299999    52
Name: age, Length: 300000, dtype: int64

In [40]:
display(Citi_Bike['age'].max())

np.int64(133)

In [41]:
Citi_Bike = Citi_Bike.drop(['birth year'], axis=1) 
Citi_Bike.info()

<class 'pandas.DataFrame'>
RangeIndex: 300000 entries, 0 to 299999
Data columns (total 12 columns):
 #   Column                   Non-Null Count   Dtype
---  ------                   --------------   -----
 0   starttime                300000 non-null  str
 1   stoptime                 300000 non-null  str
 2   start station name       299831 non-null  str
 3   start station latitude   300000 non-null  float64
 4   start station longitude  300000 non-null  float64
 5   end station name         299831 non-null  str
 6   end station latitude     300000 non-null  float64
 7   end station longitude    300000 non-null  float64
 8   bikeid                   300000 non-null  int64
 9   usertype                 300000 non-null  str
 10  gender                   300000 non-null  int64
 11  age                      300000 non-null  int64
dtypes: float64(4), int64(3), str(5)
memory usage: 27.5 MB

In [42]:
mask = Citi_Bike['age'] > 60
display(Citi_Bike[mask])

,starttime,stoptime,start station name,start station latitude,start station longitude,end station name,end station latitude,end station longitude,bikeid,usertype,gender,age
53,2018-09-01 00:04:20.9200,2018-09-01 00:11:21.6180,Grand Army Plaza & Central Park S,40.764397,-73.973715,Broadway & W 53 St,40.763441,-73.982681,24824,Subscriber,2,63
373,2018-09-01 00:25:47.6740,2018-09-01 00:39:31.7160,Mott St & Prince St,40.723180,-73.994800,Mott St & Prince St,40.723180,-73.994800,26083,Subscriber,2,68
405,2018-09-01 00:29:10.1630,2018-09-01 00:44:08.6110,Avenue D & E 3 St,40.720828,-73.977932,Avenue D & E 12 St,40.725806,-73.974225,33436,Subscriber,2,61
435,2018-09-01 00:31:21.7250,2018-09-01 00:41:57.9200,Broadway & W 56 St,40.765265,-73.981923,W 37 St & 10 Ave,40.756604,-73.997901,19894,Subscriber,2,63
457,2018-09-01 00:33:19.8080,2018-09-01 00:37:29.9270,Warren St & Court St,40.686371,-73.993833,Bond St & Bergen St,40.684967,-73.986208,34173,Subscriber,1,118
...,...,...,...,...,...,...,...,...,...,...,...,...
299882,2018-09-05 19:07:25.4010,2018-09-05 19:35:36.5000,Amsterdam Ave & W 66 St,40.774667,-73.984706,Cathedral Pkwy & Broadway,40.804213,-73.966991,16376,Subscriber,1,64
299883,2018-09-05 19:07:24.9130,2018-09-05 19:20:20.2760,W 4 St & 7 Ave S,40.734011,-74.002939,E 2 St & Avenue A,40.723077,-73.985836,29943,Subscriber,2,70
299946,2018-09-05 19:08:06.4620,2018-09-05 19:20:16.0180,Henry St & Grand St,40.714215,-73.981346,Lafayette St & E 8 St,40.730207,-73.991026,30951,Subscriber,1,71
299957,2018-09-05 19:08:12.5770,2018-09-05 19:42:24.0340,Market St & Cherry St,40.710762,-73.994004,Catherine St & Monroe St,40.711174,-73.996826,31453,Subscriber,1,76
299990,2018-09-05 19:08:26.2640,2018-09-05 19:44:53.7800,Columbus Ave & W 72 St,40.777057,-73.978985,Hudson St & Reade St,40.716250,-74.009106,26377,Subscriber,1,66

Задание 6.10

Создайте признак длительности поездки trip duration. Для этого вычислите интервал времени между временем окончания поездки (stoptime) и её началом (starttime). Сколько целых минут длилась поездка под индексом 3 в таблице?

In [43]:
Citi_Bike['starttime'] = pd.to_datetime(Citi_Bike['starttime'], dayfirst=False)
display(Citi_Bike['starttime'])

0        2018-09-01 00:00:05.269
1        2018-09-01 00:00:11.281
2        2018-09-01 00:00:20.649
3        2018-09-01 00:00:21.746
4        2018-09-01 00:00:27.315
                   ...
299995   2018-09-05 19:08:27.846
299996   2018-09-05 19:08:28.370
299997   2018-09-05 19:08:27.509
299998   2018-09-05 19:08:29.230
299999   2018-09-05 19:08:29.711
Name: starttime, Length: 300000, dtype: datetime64[us]

In [44]:
Citi_Bike['stoptime'] = pd.to_datetime(Citi_Bike['stoptime'], dayfirst=False)
display(Citi_Bike['stoptime'])

0        2018-09-01 00:27:20.634
1        2018-09-01 00:02:23.481
2        2018-09-01 00:55:58.547
3        2018-09-01 00:07:38.583
4        2018-09-01 02:21:25.308
                   ...
299995   2018-09-05 19:15:51.494
299996   2018-09-05 19:20:01.508
299997   2018-09-05 19:13:40.506
299998   2018-09-05 20:04:29.322
299999   2018-09-05 19:12:14.762
Name: stoptime, Length: 300000, dtype: datetime64[us]

In [45]:
Citi_Bike['trip_duration'] = Citi_Bike['stoptime'] - Citi_Bike['starttime']
display(Citi_Bike['trip_duration'][3])

Timedelta('0 days 00:07:16.837000')

In [46]:
Citi_Bike.info()

<class 'pandas.DataFrame'>
RangeIndex: 300000 entries, 0 to 299999
Data columns (total 13 columns):
 #   Column                   Non-Null Count   Dtype
---  ------                   --------------   -----
 0   starttime                300000 non-null  datetime64[us]
 1   stoptime                 300000 non-null  datetime64[us]
 2   start station name       299831 non-null  str
 3   start station latitude   300000 non-null  float64
 4   start station longitude  300000 non-null  float64
 5   end station name         299831 non-null  str
 6   end station latitude     300000 non-null  float64
 7   end station longitude    300000 non-null  float64
 8   bikeid                   300000 non-null  int64
 9   usertype                 300000 non-null  str
 10  gender                   300000 non-null  int64
 11  age                      300000 non-null  int64
 12  trip_duration            300000 non-null  timedelta64[us]
dtypes: datetime64[us](2), float64(4), int64(3), str(3), timedelta64[us](1)
memory usage: 29.8 MB

Задание 6.11

Создайте «признак-мигалку» weekend, который равен 1, если поездка начиналась в выходной день (суббота или воскресенье), и 0 — в противном случае. Выясните, сколько поездок начиналось в выходные.

In [47]:
mask_weekend = (Citi_Bike['starttime'].dt.dayofweek == 5) | (Citi_Bike['starttime'].dt.dayofweek == 6)
Citi_Bike[mask_weekend]

,starttime,stoptime,start station name,start station latitude,start station longitude,end station name,end station latitude,end station longitude,bikeid,usertype,gender,age,trip_duration
0,2018-09-01 00:00:05.269,2018-09-01 00:27:20.634,MacDougal St & Washington Sq,40.732264,-73.998522,Clinton Ave & Myrtle Ave,40.693261,-73.968896,25577,Subscriber,1,38,0 days 00:27:15.365000
1,2018-09-01 00:00:11.281,2018-09-01 00:02:23.481,Cadman Plaza West & Montague St,40.693830,-73.990539,Schermerhorn St & Court St,40.691029,-73.991834,34377,Subscriber,0,49,0 days 00:02:12.200000
2,2018-09-01 00:00:20.649,2018-09-01 00:55:58.547,1 Ave & E 62 St,40.761227,-73.960940,Smith St & 3 St,40.678724,-73.995991,30496,Subscriber,1,43,0 days 00:55:37.898000
3,2018-09-01 00:00:21.746,2018-09-01 00:07:38.583,St James Pl & Oliver St,40.713079,-73.998512,Park Pl & Church St,40.713342,-74.009355,28866,Subscriber,2,34,0 days 00:07:16.837000
4,2018-09-01 00:00:27.315,2018-09-01 02:21:25.308,W 13 St & 6 Ave,40.736494,-73.997044,W 4 St & 7 Ave S,40.734011,-74.002939,20943,Customer,1,24,0 days 02:20:57.993000
...,...,...,...,...,...,...,...,...,...,...,...,...,...
248507,2018-09-01 19:01:39.660,2018-09-01 19:09:34.516,Concord St & Bridge St,40.697666,-73.984764,Front St & Washington St,40.702551,-73.989402,27688,Subscriber,1,31,0 days 00:07:54.856000
248516,2018-09-01 21:53:55.244,2018-09-01 21:59:19.266,Concord St & Bridge St,40.697666,-73.984764,Front St & Washington St,40.702551,-73.989402,14909,Subscriber,1,32,0 days 00:05:24.022000
248520,2018-09-02 09:46:26.247,2018-09-02 09:51:56.662,Concord St & Bridge St,40.697666,-73.984764,Pearl St & Anchorage Pl,40.702819,-73.987658,25959,Subscriber,1,31,0 days 00:05:30.415000
248525,2018-09-02 09:55:13.467,2018-09-02 10:01:29.366,Concord St & Bridge St,40.697666,-73.984764,Cadman Plaza West & Montague St,40.693830,-73.990539,16371,Subscriber,1,32,0 days 00:06:15.899000
248549,2018-09-02 16:18:31.305,2018-09-02 16:36:00.042,Concord St & Bridge St,40.697666,-73.984764,4 Ave & 9 St,40.670513,-73.988766,21282,Subscriber,1,31,0 days 00:17:28.737000

In [48]:
day = Citi_Bike['starttime'].dt.dayofweek
display(day)

0         5
1         5
2         5
3         5
4         5
         ..
299995    2
299996    2
299997    2
299998    2
299999    2
Name: starttime, Length: 300000, dtype: int32

In [49]:
def weekend_func(day):
    if day == 5 or day == 6:
        return 1
    else:
        return 0
    
#weekend_func(Citi_Bike['starttime'].iloc[1])

In [50]:
Citi_Bike['weekend'] = day.apply(weekend_func)
display(Citi_Bike['weekend'])

0         1
1         1
2         1
3         1
4         1
         ..
299995    0
299996    0
299997    0
299998    0
299999    0
Name: weekend, Length: 300000, dtype: int64

In [51]:
display(Citi_Bike['weekend'].value_counts(normalize=True))

weekend
0    0.616217
1    0.383783
Name: proportion, dtype: float64

In [52]:
display(Citi_Bike.head())

,starttime,stoptime,start station name,start station latitude,start station longitude,end station name,end station latitude,end station longitude,bikeid,usertype,gender,age,trip_duration,weekend
0,2018-09-01 00:00:05.269,2018-09-01 00:27:20.634,MacDougal St & Washington Sq,40.732264,-73.998522,Clinton Ave & Myrtle Ave,40.693261,-73.968896,25577,Subscriber,1,38,0 days 00:27:15.365000,1
1,2018-09-01 00:00:11.281,2018-09-01 00:02:23.481,Cadman Plaza West & Montague St,40.693830,-73.990539,Schermerhorn St & Court St,40.691029,-73.991834,34377,Subscriber,0,49,0 days 00:02:12.200000,1
2,2018-09-01 00:00:20.649,2018-09-01 00:55:58.547,1 Ave & E 62 St,40.761227,-73.960940,Smith St & 3 St,40.678724,-73.995991,30496,Subscriber,1,43,0 days 00:55:37.898000,1
3,2018-09-01 00:00:21.746,2018-09-01 00:07:38.583,St James Pl & Oliver St,40.713079,-73.998512,Park Pl & Church St,40.713342,-74.009355,28866,Subscriber,2,34,0 days 00:07:16.837000,1
4,2018-09-01 00:00:27.315,2018-09-01 02:21:25.308,W 13 St & 6 Ave,40.736494,-73.997044,W 4 St & 7 Ave S,40.734011,-74.002939,20943,Customer,1,24,0 days 02:20:57.993000,1

Задание 6.12

Создайте признак времени суток поездки time_of_day. Время суток будем определять из часа начала поездки. 

Условимся, что:

поездка совершается ночью (night), если её час приходится на интервал от 0 (включительно) до 6 (включительно) часов;

поездка совершается утром (morning), если её час приходится на интервал от 6 (не включительно) до 12 (включительно) часов;

поездка совершается днём (day), если её час приходится на интервал от 12 (не включительно) до 18 (включительно) часов;

поездка совершается вечером (evening), если её час приходится на интервал от 18 (не включительно) до 23 часов (включительно).

Во сколько раз количество поездок, совершённых днём, больше, чем количество поездок, совёршенных ночью, за представленный в данных период времени? Ответ округлите до целых.

In [53]:
hour = Citi_Bike['starttime'].dt.hour
display(hour)

0          0
1          0
2          0
3          0
4          0
          ..
299995    19
299996    19
299997    19
299998    19
299999    19
Name: starttime, Length: 300000, dtype: int32

In [54]:
#поездка совершается ночью (night), если её час приходится на интервал от 0 (включительно) до 6 (включительно) часов
night = ((hour >= 0) & (hour <= 6)) 
#утром (morning), если её час приходится на интервал от 6 (не включительно) до 12 (включительно) часов
morning = ((hour > 6) & (hour <= 12)) 
#днём (day), если её час приходится на интервал от 12 (не включительно) до 18 (включительно) часов
day = ((hour > 12) & (hour <= 18)) 
#вечером (evening), если её час приходится на интервал от 18 (не включительно) до 23 часов (включительно).
evening = ((hour > 18) & (hour <= 23)) 
display(Citi_Bike[day])

,starttime,stoptime,start station name,start station latitude,start station longitude,end station name,end station latitude,end station longitude,bikeid,usertype,gender,age,trip_duration,weekend
18458,2018-09-01 13:00:01.772,2018-09-01 13:06:04.514,Broadway & E 14 St,40.734546,-73.990741,Mercer St & Bleecker St,40.727064,-73.996621,19994,Subscriber,1,31,0 days 00:06:02.742000,1
18459,2018-09-01 13:00:02.355,2018-09-01 13:28:07.574,W 78 St & Broadway,40.783400,-73.980931,5 Ave & E 93 St,40.785785,-73.957481,20162,Customer,0,49,0 days 00:28:05.219000,1
18460,2018-09-01 13:00:03.992,2018-09-01 13:05:16.564,Lewis Ave & Madison St,40.686312,-73.935775,Kosciuszko St & Tompkins Ave,40.691283,-73.945242,28166,Subscriber,1,31,0 days 00:05:12.572000,1
18461,2018-09-01 13:00:02.942,2018-09-01 13:14:03.934,W 50 St & 9 Ave,40.763605,-73.989180,8 Ave & W 33 St,40.751551,-73.993934,16285,Subscriber,1,52,0 days 00:14:00.992000,1
18462,2018-09-01 13:00:07.936,2018-09-01 13:38:58.570,E 51 St & Lexington Ave,40.757148,-73.972078,2 Ave & E 122 St,40.800672,-73.934900,33748,Customer,1,23,0 days 00:38:50.634000,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
299042,2018-09-05 18:59:58.147,2018-09-05 19:36:26.202,W 33 St & 7 Ave,40.750200,-73.990931,Grand St & Havemeyer St,40.712868,-73.956981,18418,Subscriber,2,29,0 days 00:36:28.055000,0
299043,2018-09-05 18:59:59.215,2018-09-05 19:35:09.393,W 50 St & 9 Ave,40.763605,-73.989180,East End Ave & E 86 St,40.775186,-73.944461,27172,Subscriber,2,25,0 days 00:35:10.178000,0
299044,2018-09-05 18:59:58.810,2018-09-05 19:15:03.209,Grand St & Greene St,40.721655,-74.002347,Pearl St & Hanover Square,40.704718,-74.009260,14958,Subscriber,2,27,0 days 00:15:04.399000,0
299045,2018-09-05 18:59:58.964,2018-09-05 19:08:30.006,46 Ave & 5 St,40.747310,-73.954510,Queens Plaza North & Crescent St,40.751102,-73.940737,14947,Subscriber,0,49,0 days 00:08:31.042000,0
299048,2018-09-05 18:59:59.703,2018-09-05 19:05:05.041,MacDougal St & Prince St,40.727103,-74.002971,Greenwich Ave & Charles St,40.735238,-74.000271,30597,Subscriber,1,58,0 days 00:05:05.338000,0

In [55]:
Citi_Bike.sort_values(by = 'trip_duration', ascending=True).head(5)

,starttime,stoptime,start station name,start station latitude,start station longitude,end station name,end station latitude,end station longitude,bikeid,usertype,gender,age,trip_duration,weekend
92487,2018-09-02 16:55:22.305,2018-09-02 16:56:23.348,Picnic Point,40.685126,-74.025353,Picnic Point,40.685126,-74.025353,31785,Customer,0,49,0 days 00:01:01.043000,1
89573,2018-09-02 16:19:56.024,2018-09-02 16:20:57.136,E 78 St & 2 Ave,40.772797,-73.955778,E 78 St & 2 Ave,40.772797,-73.955778,30738,Customer,2,28,0 days 00:01:01.112000,1
118061,2018-09-03 07:41:49.122,2018-09-03 07:42:50.256,Broadway & Battery Pl,40.704633,-74.013617,Water - Whitehall Plaza,40.702551,-74.012723,28083,Subscriber,1,30,0 days 00:01:01.134000,0
254774,2018-09-05 08:59:45.338,2018-09-05 09:00:46.492,W 64 St & Thelonious Monk Circle,40.775160,-73.989187,W 64 St & Thelonious Monk Circle,40.775160,-73.989187,18613,Subscriber,1,25,0 days 00:01:01.154000,0
93657,2018-09-02 17:08:32.871,2018-09-02 17:09:34.060,W 15 St & 10 Ave,40.742754,-74.007474,W 16 St & The High Line,40.743349,-74.006818,25248,Subscriber,2,33,0 days 00:01:01.189000,1

In [56]:
display(Citi_Bike[night])

,starttime,stoptime,start station name,start station latitude,start station longitude,end station name,end station latitude,end station longitude,bikeid,usertype,gender,age,trip_duration,weekend
0,2018-09-01 00:00:05.269,2018-09-01 00:27:20.634,MacDougal St & Washington Sq,40.732264,-73.998522,Clinton Ave & Myrtle Ave,40.693261,-73.968896,25577,Subscriber,1,38,0 days 00:27:15.365000,1
1,2018-09-01 00:00:11.281,2018-09-01 00:02:23.481,Cadman Plaza West & Montague St,40.693830,-73.990539,Schermerhorn St & Court St,40.691029,-73.991834,34377,Subscriber,0,49,0 days 00:02:12.200000,1
2,2018-09-01 00:00:20.649,2018-09-01 00:55:58.547,1 Ave & E 62 St,40.761227,-73.960940,Smith St & 3 St,40.678724,-73.995991,30496,Subscriber,1,43,0 days 00:55:37.898000,1
3,2018-09-01 00:00:21.746,2018-09-01 00:07:38.583,St James Pl & Oliver St,40.713079,-73.998512,Park Pl & Church St,40.713342,-74.009355,28866,Subscriber,2,34,0 days 00:07:16.837000,1
4,2018-09-01 00:00:27.315,2018-09-01 02:21:25.308,W 13 St & 6 Ave,40.736494,-73.997044,W 4 St & 7 Ave S,40.734011,-74.002939,20943,Customer,1,24,0 days 02:20:57.993000,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
248566,2018-09-03 06:53:57.358,2018-09-03 07:00:14.405,Concord St & Bridge St,40.697666,-73.984764,State St & Smith St,40.689269,-73.989129,30314,Subscriber,1,36,0 days 00:06:17.047000,0
248613,2018-09-04 06:31:57.529,2018-09-04 06:38:47.265,Concord St & Bridge St,40.697666,-73.984764,Fulton St & Rockwell Pl,40.688226,-73.979382,19439,Subscriber,1,35,0 days 00:06:49.736000,0
248618,2018-09-04 06:55:45.254,2018-09-04 07:17:26.319,Concord St & Bridge St,40.697666,-73.984764,Water - Whitehall Plaza,40.702551,-74.012723,27971,Subscriber,2,35,0 days 00:21:41.065000,0
248696,2018-09-05 06:34:40.080,2018-09-05 06:53:14.553,Concord St & Bridge St,40.697666,-73.984764,Maiden Ln & Pearl St,40.707065,-74.007319,27055,Subscriber,2,35,0 days 00:18:34.473000,0
248699,2018-09-05 06:47:02.806,2018-09-05 06:53:52.776,Concord St & Bridge St,40.697666,-73.984764,Pearl St & Anchorage Pl,40.702819,-73.987658,25404,Subscriber,2,36,0 days 00:06:49.970000,0

In [57]:
display(Citi_Bike.head())

,starttime,stoptime,start station name,start station latitude,start station longitude,end station name,end station latitude,end station longitude,bikeid,usertype,gender,age,trip_duration,weekend
0,2018-09-01 00:00:05.269,2018-09-01 00:27:20.634,MacDougal St & Washington Sq,40.732264,-73.998522,Clinton Ave & Myrtle Ave,40.693261,-73.968896,25577,Subscriber,1,38,0 days 00:27:15.365000,1
1,2018-09-01 00:00:11.281,2018-09-01 00:02:23.481,Cadman Plaza West & Montague St,40.693830,-73.990539,Schermerhorn St & Court St,40.691029,-73.991834,34377,Subscriber,0,49,0 days 00:02:12.200000,1
2,2018-09-01 00:00:20.649,2018-09-01 00:55:58.547,1 Ave & E 62 St,40.761227,-73.960940,Smith St & 3 St,40.678724,-73.995991,30496,Subscriber,1,43,0 days 00:55:37.898000,1
3,2018-09-01 00:00:21.746,2018-09-01 00:07:38.583,St James Pl & Oliver St,40.713079,-73.998512,Park Pl & Church St,40.713342,-74.009355,28866,Subscriber,2,34,0 days 00:07:16.837000,1
4,2018-09-01 00:00:27.315,2018-09-01 02:21:25.308,W 13 St & 6 Ave,40.736494,-73.997044,W 4 St & 7 Ave S,40.734011,-74.002939,20943,Customer,1,24,0 days 02:20:57.993000,1

--------------------

In [58]:
import pandas as pd

In [59]:
ratings_movies = pd.read_csv('data/ratings_movies.csv', sep=',')
display(ratings_movies.head(3))

,Unnamed: 0,userId,movieId,rating,date,title,genres
0,0,1,1,4.0,2000-07-30 18:45:03,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
1,1,1,3,4.0,2000-07-30 18:20:47,Grumpier Old Men (1995),Comedy|Romance
2,2,1,6,4.0,2000-07-30 18:37:04,Heat (1995),Action|Crime|Thriller

Для решения задач нам понадобится выделить из признака title год выпуска фильма. Для этого напишем функцию get_year_release(arg).

In [ ]:
#библиотека для регулярных выражений
import re 
def get_year_release(arg):
    #находим все слова по шаблону "(DDDD)"
    candidates = re.findall(r'\(\d{4}\)', arg) 
    # проверяем число вхождений
    if len(candidates) > 0:
        #если число вхождений больше 0,
	#очищаем строку от знаков "(" и ")"
        year = candidates[0].replace('(', '')
        year = year.replace(')', '')
        return int(year)
    else:
        #если год не указан, возвращаем None
        
        return None

Задание 8.1

Создайте в таблице новый признак year_release, который соответствует году выпуска фильма.
У скольких фильмов не указан год их выпуска?

In [72]:
ratings_movies['year_release'] = ratings_movies['title'].apply(get_year_release)
ratings_movies['year_release'].info()

<class 'pandas.Series'>
RangeIndex: 100836 entries, 0 to 100835
Series name: year_release
Non-Null Count   Dtype
--------------   -----
100818 non-null  float64
dtypes: float64(1)
memory usage: 787.9 KB

In [68]:
mask = ratings_movies['year_release'] == None
ratings_movies[mask].shape[0]

0

Задание 8.2

Какой фильм, выпущенный в 1999 году, получил наименьшую среднюю оценку зрителей?

In [79]:
mask = ratings_movies['year_release'] == 1999
ratings_movies[mask].groupby('title')['rating'].mean().sort_values(ascending=True)

title
Bloodsport: The Dark Kumite (1999)            0.5
Simon Sez (1999)                              1.0
Chill Factor (1999)                           1.0
Source, The (1999)                            1.0
Trippin' (1999)                               1.0
                                             ...
Trailer Park Boys (1999)                      5.0
Larry David: Curb Your Enthusiasm (1999)      5.0
Sun Alley (Sonnenallee) (1999)                5.0
George Carlin: You Are All Diseased (1999)    5.0
Five Senses, The (1999)                       5.0
Name: rating, Length: 261, dtype: float64

Задание 8.3

Какое сочетание жанров фильмов (genres), выпущенных в 2010 году, получило наименьшую среднюю оценку (rating)?
Запишите сочетание так же, как оно указано в таблице (через разделитель |, без пробелов).

In [80]:
mask = ratings_movies['year_release'] == 2010
ratings_movies[mask].groupby('genres')['rating'].mean().sort_values(ascending=True)

genres
Action|Sci-Fi                        1.000000
Action|Adventure|Horror              1.500000
Action|Drama|Fantasy                 1.500000
Crime|Romance                        1.500000
Adventure|Comedy|Fantasy             1.833333
                                       ...
Crime                                4.750000
Comedy|Musical                       5.000000
Animation|Drama|Fantasy|Mystery      5.000000
Adventure|Children|Comedy|Mystery    5.000000
Animation|Children|Mystery           5.000000
Name: rating, Length: 119, dtype: float64

Задание 8.4

Какой пользователь (userId) посмотрел наибольшее количество различных (уникальных) комбинаций жанров (genres) фильмов? В качестве ответа запишите идентификатор этого пользователя.

In [86]:
ratings_movies.groupby('userId')['genres'].nunique().sort_values(ascending=False)

userId
599    524
414    482
448    403
380    399
474    395
      ...
578     15
12      15
85      13
214     13
245     13
Name: genres, Length: 610, dtype: int64

Задание 8.5

Найдите пользователя, который выставил наименьшее количество оценок, но его средняя оценка фильмам наибольшая.
В качестве ответа укажите идентификатор этого пользователя

In [96]:
ratings_movies.groupby('userId')['rating'].agg(
    ['count', 'mean']
).sort_values(['count', 'mean'], ascending=[True, False])

        count      mean
userId
53         20  5.000000
595        20  4.200000
189        20  4.100000
569        20  4.000000
278        20  3.875000
...       ...       ...
274      1346  3.235884
448      1864  2.847371
474      2108  3.398956
599      2478  2.642050
414      2698  3.391957

[610 rows x 2 columns]

Задание 8.6

Найдите сочетание жанров (genres) за 2018 год, которое имеет наибольший средний рейтинг (среднее по столбцу rating), и при этом число выставленных ему оценок (количество значений в столбце rating) больше 10.
Запишите сочетание так же, как оно указано в таблице (через разделитель |, без пробелов).

In [98]:
mask = ratings_movies['year_release'] == 2018
grouped = ratings_movies[mask].groupby('genres')['rating'].agg(
    ['mean', 'count']
)
grouped[grouped['count']>10].sort_values(
    by='mean',
    ascending=False
)

                             mean  count
genres
Action|Adventure|Sci-Fi  3.928571     14
Action|Comedy|Sci-Fi     3.875000     12

Задание 8.7

Добавьте в таблицу новый признак year_rating — год выставления оценки. Создайте сводную таблицу, которая иллюстрирует зависимость среднего рейтинга фильма от года выставления оценки и жанра.

In [104]:
ratings_movies['date'] = pd.to_datetime(ratings_movies['date'], dayfirst=False)
ratings_movies['year_rating'] = ratings_movies['date'].dt.year

In [106]:
ratings_movies.pivot_table(
    values='rating',
    index='year_rating',
    columns='genres',
    fill_value=0
)

genres,(no genres listed),Action,Action|Adventure,Action|Adventure|Animation,Action|Adventure|Animation|Children,Action|Adventure|Animation|Children|Comedy,Action|Adventure|Animation|Children|Comedy|Fantasy,Action|Adventure|Animation|Children|Comedy|IMAX,Action|Adventure|Animation|Children|Comedy|Romance,Action|Adventure|Animation|Children|Comedy|Sci-Fi,...,Romance|Thriller,Romance|War,Romance|Western,Sci-Fi,Sci-Fi|IMAX,Sci-Fi|Thriller,Sci-Fi|Thriller|IMAX,Thriller,War,Western
year_rating,,,,,,,,,,,,,,,,,,,,,
1996,0.000000,2.730769,3.454545,0.000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,...,0.000,0.0,0.0,0.000000,0.000000,2.666667,0.000000,3.838095,0.0,3.117647
1997,0.000000,3.538462,4.150000,0.000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,...,0.000,0.0,0.0,0.000000,0.000000,3.400000,0.000000,3.923077,0.0,3.000000
1998,0.000000,0.000000,4.200000,0.000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,...,0.000,0.0,0.0,0.000000,0.000000,0.000000,0.000000,3.800000,0.0,0.000000
1999,0.000000,0.000000,4.000000,0.000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,...,2.000,0.0,0.0,0.000000,0.000000,4.000000,0.000000,3.700000,4.5,4.000000
2000,0.000000,2.588235,3.738462,0.000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,...,4.000,0.0,3.0,3.416667,0.000000,2.142857,0.000000,3.087912,3.0,4.058824
2001,0.000000,3.000000,3.500000,0.000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,...,0.000,0.0,3.0,2.500000,0.000000,2.500000,0.000000,3.477273,3.0,3.111111
2002,0.000000,2.750000,4.304348,0.000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,...,3.000,0.0,0.0,3.750000,0.000000,3.600000,0.000000,3.583333,3.5,3.000000
2003,0.000000,3.833333,3.277778,0.000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,...,3.375,2.5,0.0,2.333333,0.000000,3.142857,0.000000,3.250000,3.0,4.000000
2004,0.000000,2.700000,4.136364,0.000,0.000000,4.000000,0.000000,0.000000,0.000000,0.0,...,3.000,3.0,3.5,2.125000,0.000000,0.000000,0.000000,3.464286,3.0,3.800000
2005,0.000000,3.357143,3.413043,0.000,0.000000,4.107143,0.000000,0.000000,0.000000,0.0,...,2.000,0.0,0.0,3.000000,0.000000,2.750000,0.000000,3.411765,0.0,4.500000
2006,0.000000,2.166667,4.090909,0.000,0.000000,3.833333,0.000000,0.000000,0.000000,3.0,...,0.000,0.0,0.0,0.500000,0.000000,4.500000,0.000000,3.735294,0.0,3.625000
2007,0.000000,2.583333,3.666667,0.000,0.000000,3.846154,3.000000,0.000000,0.000000,2.8,...,1.500,0.0,2.5,3.375000,0.000000,2.833333,0.000000,3.421875,0.0,3.000000
2008,0.000000,3.000000,3.656250,0.000,0.000000,4.125000,4.000000,0.000000,0.000000,3.5,...,0.000,0.0,0.0,3.125000,0.000000,3.000000,0.000000,3.333333,0.0,4.000000
2009,0.000000,0.000000,3.714286,0.000,0.000000,3.900000,0.000000,3.250000,0.000000,2.5,...,0.000,0.0,0.0,2.000000,0.000000,4.000000,0.000000,2.964286,4.0,3.375000
2010,0.000000,3.500000,3.437500,0.000,0.000000,4.333333,0.000000,3.500000,3.000000,0.0,...,0.000,0.0,0.0,4.000000,0.000000,2.500000,0.000000,2.833333,0.0,3.666667
2011,0.000000,4.500000,3.888889,0.000,0.000000,3.500000,0.000000,0.000000,0.000000,4.0,...,0.000,0.0,0.0,3.500000,0.000000,1.833333,4.000000,3.625000,0.0,4.000000
2012,0.000000,2.625000,3.900000,0.000,4.000000,3.785714,0.000000,3.550000,4.000000,0.0,...,2.500,0.0,0.0,4.166667,0.000000,3.500000,3.666667,3.083333,0.0,4.100000
2013,0.000000,2.500000,3.833333,0.000,3.000000,4.333333,0.000000,5.000000,0.000000,0.0,...,0.000,0.0,0.0,1.500000,0.000000,3.833333,4.000000,3.666667,0.0,4.000000
2014,0.000000,0.000000,3.875000,3.000,3.500000,3.250000,3.833333,3.500000,4.000000,0.0,...,0.000,0.0,0.0,2.500000,5.000000,0.000000,4.000000,4.000000,0.0,4.000000
2015,0.500000,3.100000,3.560976,3.800,3.666667,3.565217,3.833333,3.375000,2.333333,2.5,...,0.000,0.0,0.0,2.900000,4.071429,3.764706,4.000000,2.911765,0.0,3.900000
2016,3.500000,3.545455,3.722222,3.750,3.833333,3.925000,3.388889,3.666667,1.000000,4.0,...,2.500,0.0,0.0,3.555556,3.807692,3.916667,3.666667,3.432432,0.0,3.958333
2017,3.000000,2.637931,3.527778,3.375,3.500000,3.676471,3.700000,1.000000,1.000000,2.0,...,3.000,0.0,0.0,3.864865,4.264706,3.750000,2.500000,3.152174,0.0,2.933333
2018,3.676471,2.588235,3.397436,3.650,3.166667,3.741935,4.142857,3.700000,2.500000,4.0,...,0.000,0.0,0.0,3.128571,3.500000,3.562500,0.000000,3.296296,0.0,3.611111

In [107]:
ratings_movies['date'] = pd.to_datetime(ratings_movies['date'])
ratings_movies['year_rating'] = ratings_movies['date'].dt.year
pivot = ratings_movies.pivot_table(
    index='year_rating',
    columns='genres',
    values='rating',
    aggfunc='mean'
)
display(pivot)

genres,(no genres listed),Action,Action|Adventure,Action|Adventure|Animation,Action|Adventure|Animation|Children,Action|Adventure|Animation|Children|Comedy,Action|Adventure|Animation|Children|Comedy|Fantasy,Action|Adventure|Animation|Children|Comedy|IMAX,Action|Adventure|Animation|Children|Comedy|Romance,Action|Adventure|Animation|Children|Comedy|Sci-Fi,...,Romance|Thriller,Romance|War,Romance|Western,Sci-Fi,Sci-Fi|IMAX,Sci-Fi|Thriller,Sci-Fi|Thriller|IMAX,Thriller,War,Western
year_rating,,,,,,,,,,,,,,,,,,,,,
1996,NaN,2.730769,3.454545,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,2.666667,NaN,3.838095,NaN,3.117647
1997,NaN,3.538462,4.150000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,3.400000,NaN,3.923077,NaN,3.000000
1998,NaN,NaN,4.200000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.800000,NaN,NaN
1999,NaN,NaN,4.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2.000,NaN,NaN,NaN,NaN,4.000000,NaN,3.700000,4.5,4.000000
2000,NaN,2.588235,3.738462,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,4.000,NaN,3.0,3.416667,NaN,2.142857,NaN,3.087912,3.0,4.058824
2001,NaN,3.000000,3.500000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,3.0,2.500000,NaN,2.500000,NaN,3.477273,3.0,3.111111
2002,NaN,2.750000,4.304348,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,3.000,NaN,NaN,3.750000,NaN,3.600000,NaN,3.583333,3.5,3.000000
2003,NaN,3.833333,3.277778,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,3.375,2.5,NaN,2.333333,NaN,3.142857,NaN,3.250000,3.0,4.000000
2004,NaN,2.700000,4.136364,NaN,NaN,4.000000,NaN,NaN,NaN,NaN,...,3.000,3.0,3.5,2.125000,NaN,NaN,NaN,3.464286,3.0,3.800000
2005,NaN,3.357143,3.413043,NaN,NaN,4.107143,NaN,NaN,NaN,NaN,...,2.000,NaN,NaN,3.000000,NaN,2.750000,NaN,3.411765,NaN,4.500000
2006,NaN,2.166667,4.090909,NaN,NaN,3.833333,NaN,NaN,NaN,3.0,...,NaN,NaN,NaN,0.500000,NaN,4.500000,NaN,3.735294,NaN,3.625000
2007,NaN,2.583333,3.666667,NaN,NaN,3.846154,3.000000,NaN,NaN,2.8,...,1.500,NaN,2.5,3.375000,NaN,2.833333,NaN,3.421875,NaN,3.000000
2008,NaN,3.000000,3.656250,NaN,NaN,4.125000,4.000000,NaN,NaN,3.5,...,NaN,NaN,NaN,3.125000,NaN,3.000000,NaN,3.333333,NaN,4.000000
2009,NaN,NaN,3.714286,NaN,NaN,3.900000,NaN,3.250000,NaN,2.5,...,NaN,NaN,NaN,2.000000,NaN,4.000000,NaN,2.964286,4.0,3.375000
2010,NaN,3.500000,3.437500,NaN,NaN,4.333333,NaN,3.500000,3.000000,NaN,...,NaN,NaN,NaN,4.000000,NaN,2.500000,NaN,2.833333,NaN,3.666667
2011,NaN,4.500000,3.888889,NaN,NaN,3.500000,NaN,NaN,NaN,4.0,...,NaN,NaN,NaN,3.500000,NaN,1.833333,4.000000,3.625000,NaN,4.000000
2012,NaN,2.625000,3.900000,NaN,4.000000,3.785714,NaN,3.550000,4.000000,NaN,...,2.500,NaN,NaN,4.166667,NaN,3.500000,3.666667,3.083333,NaN,4.100000
2013,NaN,2.500000,3.833333,NaN,3.000000,4.333333,NaN,5.000000,NaN,NaN,...,NaN,NaN,NaN,1.500000,NaN,3.833333,4.000000,3.666667,NaN,4.000000
2014,NaN,NaN,3.875000,3.000,3.500000,3.250000,3.833333,3.500000,4.000000,NaN,...,NaN,NaN,NaN,2.500000,5.000000,NaN,4.000000,4.000000,NaN,4.000000
2015,0.500000,3.100000,3.560976,3.800,3.666667,3.565217,3.833333,3.375000,2.333333,2.5,...,NaN,NaN,NaN,2.900000,4.071429,3.764706,4.000000,2.911765,NaN,3.900000
2016,3.500000,3.545455,3.722222,3.750,3.833333,3.925000,3.388889,3.666667,1.000000,4.0,...,2.500,NaN,NaN,3.555556,3.807692,3.916667,3.666667,3.432432,NaN,3.958333
2017,3.000000,2.637931,3.527778,3.375,3.500000,3.676471,3.700000,1.000000,1.000000,2.0,...,3.000,NaN,NaN,3.864865,4.264706,3.750000,2.500000,3.152174,NaN,2.933333
2018,3.676471,2.588235,3.397436,3.650,3.166667,3.741935,4.142857,3.700000,2.500000,4.0,...,NaN,NaN,NaN,3.128571,3.500000,3.562500,NaN,3.296296,NaN,3.611111

In [114]:
pivot['Action|Adventure'].sort_values(ascending=False)

year_rating
2002    4.304348
1998    4.200000
1997    4.150000
2004    4.136364
2006    4.090909
1999    4.000000
2012    3.900000
2011    3.888889
2014    3.875000
2013    3.833333
2000    3.738462
2016    3.722222
2009    3.714286
2007    3.666667
2008    3.656250
2015    3.560976
2017    3.527778
2001    3.500000
1996    3.454545
2010    3.437500
2005    3.413043
2018    3.397436
2003    3.277778
Name: Action|Adventure, dtype: float64

In [115]:
pivot['Action|Adventure|Animation|Children|Comedy|IMAX'].sort_values(ascending=False)

year_rating
2013    5.000000
2018    3.700000
2016    3.666667
2012    3.550000
2010    3.500000
2014    3.500000
2015    3.375000
2009    3.250000
2017    1.000000
1996         NaN
1997         NaN
1998         NaN
1999         NaN
2000         NaN
2001         NaN
2002         NaN
2003         NaN
2004         NaN
2005         NaN
2006         NaN
2007         NaN
2008         NaN
2011         NaN
Name: Action|Adventure|Animation|Children|Comedy|IMAX, dtype: float64

In [122]:
pivot['year_rating'].loc['2018'].sort_values(ascending=False)

KeyError: 'year_rating'

In [124]:
pivot['Comedy'].sort_values()

year_rating
2017    2.852668
2007    2.928187
2005    2.963325
1998    3.000000
2015    3.106183
2003    3.120066
2018    3.121296
2000    3.141291
2010    3.179825
2002    3.198556
1996    3.228571
2011    3.232877
2014    3.271429
2009    3.273292
2001    3.318408
2006    3.347534
2004    3.356877
2016    3.373431
1997    3.409091
2008    3.426667
2012    3.478477
2013    3.489474
1999    3.606061
Name: Comedy, dtype: float64

----------------

In [141]:
orders = pd.read_csv('data/orders.csv', sep=';')
products = pd.read_csv('data/products.csv', sep = ';')
display(orders.head(2))
orders.shape

,Дата создания,Order ID,ID Покупателя,Статус,Оплачен,Отменен,Отгружен,ID товара,Количество
0,09.11.2019 21:55:51,9,10,"Принят, ожидается оплата",Нет,Нет,Нет,103,5
1,09.11.2019 15:05:57,8,9,"Принят, ожидается оплата",Нет,Нет,Нет,86,100

(18, 9)

In [140]:
display(products.head(2))
products.shape

   Product_ID                      Name  Price CURRENCY
0          47      Шатны Полосатый рейс   2999      RUR
1          51  Платье Аленький цветочек   4999      RUR

(14, 4)

Объедините заданные таблицы в таблицу orders_products, чтобы в результирующей таблице оказалась информация обо всех заказах, но не оказалось информации о продуктах, на которых заказов ещё не поступало.

In [146]:
orders_products = orders.merge(
    products,
    left_on='ID товара',
    right_on='Product_ID',
    how='left'
)
display(orders_products)
orders_products.shape

,Дата создания,Order ID,ID Покупателя,Статус,Оплачен,Отменен,Отгружен,ID товара,Количество,Product_ID,Name,Price,CURRENCY
0,09.11.2019 21:55:51,9,10,"Принят, ожидается оплата",Нет,Нет,Нет,103,5,103.0,"Носки Подарочные, муж",199.0,RUR
1,09.11.2019 15:05:57,8,9,"Принят, ожидается оплата",Нет,Нет,Нет,86,100,86.0,"Носки Простые, муж",45.0,RUR
2,09.11.2019 15:05:57,8,9,"Принят, ожидается оплата",Нет,Нет,Нет,104,10,104.0,"Носки Подарочные, жен",249.0,RUR
3,09.11.2019 12:50:07,7,8,"Принят, ожидается оплата",Нет,Нет,Нет,104,7,104.0,"Носки Подарочные, жен",249.0,RUR
4,09.11.2019 12:00:00,6,1,"Принят, ожидается оплата",Нет,Нет,Нет,104,5,104.0,"Носки Подарочные, жен",249.0,RUR
5,09.11.2019 12:00:00,6,1,"Принят, ожидается оплата",Нет,Нет,Нет,103,5,103.0,"Носки Подарочные, муж",199.0,RUR
6,08.11.2019 08:36:22,5,5,Отменён,Нет,Да,Нет,124,1,124.0,Носки беговые Camino,999.0,RUR
7,08.11.2019 08:36:22,4,9,"Принят, ожидается оплата",Нет,Нет,Да,91,1,91.0,"Носки Честные, муж",50.0,RUR
8,08.11.2019 08:36:22,3,8,"Оплачен, формируется к отправке",Да,Нет,Нет,103,3,103.0,"Носки Подарочные, муж",199.0,RUR
9,08.11.2019 08:36:22,3,8,"Оплачен, формируется к отправке",Да,Нет,Нет,104,3,104.0,"Носки Подарочные, жен",249.0,RUR
10,08.11.2019 08:36:21,2,7,Выполнен,Да,Нет,Да,74,1,74.0,Платье Ночная Жизнь XXXL,8999.0,RUR
11,08.11.2019 08:36:21,2,7,Выполнен,Да,Нет,Да,53,1,53.0,Штаны Цветочная Поляна,4999.0,RUR
12,08.11.2019 08:36:21,2,7,Выполнен,Да,Нет,Да,137,1,137.0,Гольфы детские Снегурочка,99.0,RUR
13,08.11.2019 08:36:21,2,7,Выполнен,Да,Нет,Да,47,1,47.0,Шатны Полосатый рейс,2999.0,RUR
14,08.11.2019 08:36:20,1,5,"Оплачен, формируется к отправке",Да,Нет,Нет,71,1,71.0,Платье Ночная Жизнь,7999.0,RUR
15,08.11.2019 08:36:20,1,5,"Оплачен, формируется к отправке",Да,Нет,Нет,86,1,86.0,"Носки Простые, муж",45.0,RUR
16,08.11.2019 08:36:20,1,5,"Оплачен, формируется к отправке",Да,Нет,Нет,51,1,51.0,Платье Аленький цветочек,4999.0,RUR
17,01.01.2001 00:00:00,0,1,"Оплачен, формируется к отправке",Да,Нет,Нет,666,1,NaN,NaN,NaN,NaN

(18, 13)

Задание 8.10

Какой покупатель принёс наибольшую суммарную прибыль интернет-магазину за указанный период?
В ответ запишите идентификатор этого покупателя (ID Покупателя).
Прибыль состоит только из оплаченных заказов и рассчитывается как количество купленного товара, умноженное на его цену.